// ==UserScript==
// @name         Rent Filter
// @description  A Word Filter Script with MutationObserver and GTM Safety
// @author       Wapply
// @namespace    http://tampermonkey.net/
// @updateURL    https://raw.githubusercontent.com/Wapply/word-filter/main/rent-filter.user.js
// @downloadURL  https://raw.githubusercontent.com/Wapply/word-filter/main/rent-filter.user.js
// @version      5.2
// @match        *://*/*
// @grant        GM_setValue
// @grant        GM_getValue
// @grant        GM_addStyle
// ==/UserScript==

(function () {
    'use strict';

    // List of streets (sorted by length descending for better matching)
    // Includes variations for informal matching (stripped prefixes and suffixes)
    const STREETS = [
        "PASEO COSTANERO DEL SUD PRESIDENTE ARTURO HUMBERTO ILLIA", "COSTANERO DEL SUD PRESIDENTE ARTURO HUMBERTO ILLIA", "PASEO COSTANERO DEL SUD ARTURO HUMBERTO ILLIA", "\"ATAHUALPA YUPANQUI \"\"HECTOR R. CHAVERO\"\"\"", "CNO. CONSTITUCION - CNO.A LA TAPERA NORTE", "MARCELO GUSTAVO FRAGATA MARQUEZ TENIENTE", "ATAHUALPA YUPANQUI \"\"HECTOR R. CHAVERO\"\"", "DIAGONAL ESTADOS UNIDOS DE NORTEAMERICA",
        "MARIA TERESA FERRARI DE GAUDINO DOCTORA", "COSTANERO DEL SUD ARTURO HUMBERTO ILLIA", "MANUEL I. GONZALEZ GUERRICO INTENDENTE", "GIACHINO PEDRO EDUARDO CAPITAN FRAGATA", "JOSE LUIS GERONIMO CAMUSSO INTENDENTE", "HECTOR ANTONIO DUFRECHOU MAR PRIMERA", "\"ERNESTO \"\"CHE\"\" GUEVARA COMANDANTE\"", "SUD PRESIDENTE ARTURO HUMBERTO ILLIA",
        "JUANA DE IBARBOUROU JUANA FERNANDEZ", "PASAJE VECINALISTA ABELARDO MOLTENI", "CNO. COL BARRAGAN A LIMITE NORESTE", "REDUCCION NUESTRA SEÑORA DEL PILAR", "ENRIQUE RAU OBISPO MONSEÑOR DOCTOR", "NUESTRA SEÑORA DE LOS DESAMPARADOS", "CARLOS M. DELLA PAOLERA INGENIERO", "AVENIDA MIGUEL A. MARTINEZ DE HOZ",
        "DIAGONAL DALMACIO VELEZ SARSFIELD", "DIAGONAL ENRIQUE SANTOS DISCÉPOLO", "DIAGONAL GUILLERMO ENRIQUE HUDSON", "PASEO CELSO NICANOR  ALDAO DOCTOR", "MARIA TERESA FERRARI DE GAUDINO A", "CARLOS DE CHAPEAUROUGE INGENIERO", "CNO. EST. CHAPADMALAL - OTAMENDI", "CNO. EST. COBO - EA. ITUZAINGO B",
        "AVENIDA SAN MARCELINO CHAMPAGNAT", "MARADONA LAUREANO ESTEBAN DOCTOR", "MIGUEL DE ANDREA MONSEÑOR DOCTOR", "DIEGO MARTIN BELLINZONA SOLDADO", "EDUARDO RACEDO TENIENTE GENERAL", "ESTANCIA SAN JULIAN DE VIVORATA", "NUESTRA SEÑORA DE LA CONCEPCION", "CNO.A LOS PATOS - EL COYUNCO B",
        "CNO.CNIA BARRAGAN-PJE HERMANAS", "CNO.EA. LAS LOMITAS - OTAMENDI", "CNO. EST. COBO - EA. ITUZAINGO", "CNO. PARQUE HERMOSO A AEROCLUB", "CNO.STA PAULA-PJE LAS HERMANAS", "IDIOMA INTERNACIONAL ESPERANTO", "RICARDO MARIO GURRIERE SOLDADO", "TRANSPORTE ISLA DE LOS ESTADOS",
        "VICENTE MONTES CARBALLO DOCTOR", "AVENIDA PATRICIO PERALTA RAMOS", "FEDERICO C. BELTRAMI INGENIERO", "GUSTAVO MARCELO PLANES SOLDADO", "ESTADOS UNIDOS DE NORTEAMERICA", "MARQUEZ RAMON TENIENTE CORONEL", "MIGUEL ANGEL CASTELLANO DOCTOR", "PEDRO IGNACIO DE CASTRO BARROS",
        "RUTA JARDIN JUAN MANUEL FANGIO", "CARLOS EDUARDO KRAUSE CAPITAN", "CNO.ENTRADA EST. EL SOLITARIO", "CNO.EST COBO-COLONIA BARRAGAN", "CNO.S.DE LOS PADRES-V.SERRANA", "DANIEL ANTONIO JUKIC TENIENTE", "DE MARIA DAVID JEWETT CORONEL", "TEODORO SANCHEZ DE BUSTAMANTE",
        "JOSE SEVERO FELICIANO MALABIA", "RIO DE LA PLATA-BO. AUTODROMO", "ROMPE HIELOS GRAL. SAN MARTIN", "AUGUSTO CESAR SANDINO GENERAL", "AVENIDA ESTANCIA OJO DEL AGUA", "ESC. SUR - CNO. A EL SALVADOR", "JOSE ANTONIO ALVAREZ CONDARCO", "JOSE GERVASIO ARTIGAS GENERAL",
        "ESTANCIA LAGUNA DE LOS PADRES", "LIBERTADOR SAN MARTIN GENERAL", "MARIA ADELINA FUNES DE MILLAN", "MARTINEZ DE HOZ FLORENCIO BIS", "PASAJE JUAN CARLOS CASTAGNINO", "RAMIREZ  FRANCISCO J. GENERAL", "CNO. RIO PINTO - BORDEU JUAN", "CRUCERO ARA BELGRANO GENERAL",
        "DIAGONAL JUSTO ERNESTO ROMAN", "CNO.A.LAS BRUSQUITAS-L BRAVA", "CNO.A LOS PATOS - EL COYUNCO", "DIAGONAL ESTANCIA LA REFORMA", "JOSE LUIS DEL HIERRO SOLDADO", "SAN PIO DE PIETRELCINA PADRE", "AVENIDA CENTRAL ISLA SOLEDAD", "AVENIDA JUAN B. JUSTO DOCTOR",
        "BOSCH MAYOL GUILLERMO DOCTOR", "GASPAR MELCHOR DE JOVELLANOS", "JORGE ALBERTO LLAMAS SOLDADO", "JORGE NICOLAS POLITIS PILOTO", "JORGE RODOLFO DIETSCH DOCTOR", "JUAN TORRES DE VERA Y ARAGON", "ROCA JULIO ARGENTINO GENERAL", "URQUIZA JUAN JOSE DE GENERAL",
        "12 - GLORIA DE LA PELEGRINA", "14 - GLORIA DE LA PELEGRINA", "CNO.MARAYUI - EA STA ISABEL", "DIAGONAL SANTA ROSA DEL MAR", "CAMINO DEL CABILDO INDIGENA", "LUIS GUILLERMO SEVILLA CABO", "10 - GLORIA DE LA PELEGRINA", "AVENIDA ANTARTIDA ARGENTINA",
        "AVENIDA CENTENO NORBERTO O.", "AVENIDA FERMIN ERREA DOCTOR", "AVENIDA FRANCISCO QUINTEROS", "16 - GLORIA DE LA PELEGRINA", "VICTORIANO E. MONTES DOCTOR", "BRIGADIER ROSAS JUAN MANUEL", "771 BIS - PLAYA CHAPADMALAL", "\"ANIBAL TROILO \"\"PICHUCO\"\"\"",
        "EL ESTRIBO - LOMAS DEL GOLF", "CIRCUITO SAN MARTIN GENERAL", "FRANCISCO SAVERIO SCARPATTI", "GUILLERMO MARCONI INGENIERO", "JOSE ANDRES PACHECO DE MELO", "JUAN MARTIN ZABALA MONSEÑOR", "LUIS PIEDRABUENA COMANDANTE", "MARCELO T. DE ALVEAR DOCTOR",
        "OMAR ALDO FERREYRA  SOLDADO", "CELSO NICANOR  ALDAO DOCTOR", "RAMON DE LA COLINA COMODORO", "MANUEL I. GONZALEZ GUERRICO", "4 - GLORIA DE LA PELEGRINA", "6 - GLORIA DE LA PELEGRINA", "7 - GLORIA DE LA PELEGRINA", "9 - GLORIA DE LA PELEGRINA",
        "CNO. LIMITE NOROESTE NORTE", "CNO.STA PAULA - EL SOSIEGO", "COMUNIDAD FORAL DE NAVARRA", "DE DIOS FILIBERTO JUAN BIS", "DIAGONAL SANTANGELO INVADO", "CNO. A. LA TAPERA AL NORTE", "PREFECTURA NAVAL ARGENTINA", "ROLANDO PACHOLEZUK SOLDADO",
        "AVENIDA VICTORIO TETAMANTI", "BALDOMERO FERNANDEZ MORENO", "B/P VIRGEN DE LAS LAGRIMAS", "5 - GLORIA DE LA PELEGRINA", "8 - GLORIA DE LA PELEGRINA", "ALEJANDRO DACHARY TENIENTE", "ANTONIO MARIA DIAZ SOLDADO", "ENRIQUE ANGELELLI MONSEÑOR",
        "ENRIQUE FINOCHIETTO DOCTOR", "GUARDACOSTA ISLAS MALVINAS", "DIAGONAL CORTADA DEL TANGO", "JUAN JOSE  FALCONIER MAYOR", "LAS TRES MARIAS-L.DEL GOLF", "MARCELO JULIO FITTE DOCTOR", "MOSCONI ENRIQUE C. GENERAL", "NUESTRA SRA DE SCHOENSTATT",
        "JOSE LUIS GERONIMO CAMUSSO", "IBARBOUROU JUANA FERNANDEZ", "PASEO CELSO NICANOR  ALDAO", "CNO.EST CAMET - EL RETAZO", "DIAGONAL LEOPOLDO LUGONES", "DIAGONAL OVIDIO ZUBIAURRE", "TESONE JUAN OTIMIO DOCTOR", "PORTAVIONES INDEPENDENCIA",
        "REFORMA UNIVERSITARIA BIS", "PAUNERO WENCESLAO GENERAL", "TRANSPORTE BAHIA SAN BLAS", "TRANSPORTE CABO DE HORNOS", "ARTURO  MARTIN  JAURETCHE", "MIGUEL A. MARTINEZ DE HOZ", "BERNARDO NUSDORFFER PADRE", "FLORENCIO MARTINEZ DE HOZ",
        "DIAGONAL ELPIDIO GONZALEZ", "JUAN BAUTISTA DE LA SALLE", "MARIANO ACOSTA GOBERNADOR", "MARIO ABEL AMAYA DIPUTADO", "PSJE.EL CARDENAL - BQ.P.R", "PSJE.EL ZORZAL-BQ.P.RAMOS", "TOMAS MANUEL DE ANCHORENA", "ZUVIRIA MARTINEZ  GUSTAVO",
        "MARADONA LAUREANO ESTEBAN", "ANIBAL TROILO \"\"PICHUCO\"\"", "ACCESO A ESCOLLERA NORTE", "CNO.DEL CABILDO INDIGENA", "CNO.DEL CACIQUE CANGAPOL", "CNO.EL CASAL - STA CLARA", "CNO.EL TEJADO - EST COBO", "DEL VALLE MARIA REMEDIOS",
        "DIAGONAL HORACIO QUIROGA", "JOSE MARIA PIRAN GENERAL", "JUSTO SANTA MARIA DE ORO", "JUSTO S. LOPEZ DE GOMARA", "PDO. DE GRAL. PUEYRREDON", "TRIPULANTES DEL FOURNIER", "AV. DE LOS LOBOS MARINOS", "AVENIDA  DE LA HERRADURA",
        "AVENIDA JUAN HECTOR JARA", "AVENIDA PRESIDENTE PERON", "SAN MARCELINO CHAMPAGNAT", "BALDOMERO JOSE DE VIEDMA", "B/P E. SAN ANTONIO ABATE", "ALBERT SCHWEITZER DOCTOR", "ENZO BORDABEHERE SENADOR", "CIUDAD DE LAS FLORES BIS",
        "GRIERSON CECILIA DOCTORA", "DALMACIO VELEZ SARSFIELD", "ENRIQUE SANTOS DISCÉPOLO", "GUILLERMO ENRIQUE HUDSON", "JOSE COEHLO DE MEYRELLES", "ESTANCIA CABO CORRIENTES", "CELESTINO VIDAL CORONEL", "DAVID ORTEGA PRESBITERO",
        "\"DOLORES MORA \"\"LOLA\"\"\"", "HECTOR TARANTINO DOCTOR", "MANUEL N. SAVIO GENERAL", "PESQ.AMAPOLA Y ANGELITO", "REGINA PACINI DE ALVEAR", "PASEO JESUS DE GALINDEZ", "TRANSPORTE BAHIA THETIS", "AVENIDA ROBERTO J PAYRO",
        "BENITO QUINQUELA MARTIN", "BOULEVARD ABDALA GERMAN", "843 - PLAYA CHAPADMALAL", "ERNESTO SEGURA MONSEÑOR", "FRANCISCO ANGEL RIZZUTO", "GUARDACOSTAS RIO IGUAZU", "GUILLERMO BAYLEY DOCTOR", "JOSE AGUSTIN DE LA MAZA",
        "MADRE TERESA DE CALCUTA", "MARTIN MIGUEL DE GUEMES", "MARTIN SANCHEZ DE JUNCO", "MIGUEL ESTANISLAO SOLER", "PADRE GUILLERMO FURLONG", "RAFAEL DE RIEGO GENERAL", "SABINO DE ARANA Y GOIRI", "VALLE VERDE - BO. CAMET",
        "MARCELO GUSTAVO MARQUEZ", "ERNESTO \"\"CHE\"\" GUEVARA", "CARLOS M. DELLA PAOLERA", "DIEGO MARTIN BELLINZONA", "INTERNACIONAL ESPERANTO", "VICENTE MONTES CARBALLO", "MIGUEL ANGEL CASTELLANO", "ALGEL VICENTE PEÑALOZA",
        "ANDRES IGNACIO CORSINI", "CAMINO VIEJO A MIRAMAR", "SIERRA DE LOS DIFUNTOS", "DIAGONAL MANUEL CANATA", "DIAGONAL MAR DEL PLATA", "DIAGONAL RENE FAVALORO", "DIAGONAL SANTA CECILIA", "DIAGONAL ATLANTICO SUR",
        "JOSE M. CALAZA CORONEL", "JOSE RODRIGUEZ SOLDADO", "HERMANN GMEINER DOCTOR", "MANUEL ANTONIO ACEVEDO", "JULIO RATERY INGENIERO", "REPUBLICA DE SUDAFRICA", "0 CAMINO A SANTA CLARA", "VICENTE LOPEZ Y PLANES",
        "AVENIDA FELIX U. CAMET", "AVENIDA JUAN JOSE PASO", "PATRICIO PERALTA RAMOS", "BOULEVARD NUEVO BOSQUE", "VIRGEN DE LAS LAGRIMAS", "ALICIA MOREAU DE JUSTO", "ALVEAR CARLOS MARIA DE", "ANTONIO MARIA GIANELLI",
        "ELISA  ALVEAR DE BOSCH", "FEDERICO RAUCH CORONEL", "CIUDAD DE SAN CAYETANO", "GLORIA TREJON DE LOPEZ", "DIAGONAL BOSQUE GRANDE", "JERONIMO COSTA CORONEL", "JOHN FITZERALD KENNEDY", "JOSE EUSEBIO COLOMBRES",
        "JUAN BAUTISTA AZOPARDO", "JUAN CARLOS CASTAGNINO", "JUAN CONIQUEGUEN YAHAN", "JUAN DE DIOS FILIBERTO", "JUAN MADARIAGA GENERAL", "ESTANISLAO S. ZEBALLOS", "LICIO MANSILLA GENERAL", "LOS ALAMOS - BO. CAMET",
        "MARTINEZ DE HOZ MIGUEL", "LOS CEDROS - BO. CAMET", "PSJE.EL HORNERO-BQ.P.R", "PAZ JOSE MARIA GENERAL", "SUBMARINO ARA SANTA FE", "RUFINO INDA INTENDENTE", "GIACHINO PEDRO EDUARDO", "CARLOS DE CHAPEAUROUGE",
        "CHAPEAUROUGE INGENIERO", "ANDREA MONSEÑOR DOCTOR", "RICARDO MARIO GURRIERE", "GUSTAVO MARCELO PLANES", "LA PLATA-BO. AUTODROMO", "LUIS GUILLERMO SEVILLA", "AVENIDA ELIAS ANTUNEZ", "ALFREDO MARTINEZ BAYA",
        "CARLOS SAAVEDRA LAMAS", "CNO. ENTRADA. GAZZOLO", "CNO. EST. CHAPADMALAL", "CNO.NOROESTE LA BOMBA", "DE APARICIO FRANCISCO", "DE LA PLAZA FORTUNATO", "DIAGONAL HOMERO MANZI", "DIAGONAL JOSE PEDRONI",
        "DIAGONAL PLAYA SERENA", "EDUARDO PERALTA RAMOS", "ESTANCIA SAN CIPRIANO", "ESTEBAN ANGEL BONANNI", "PIONERO PETERSEN JUAN", "REFORMA UNIVERSITARIA", "REPUBLICA ARABE SIRIA", "PASEO VICTORIA OCAMPO",
        "AV. DE LOS PESCADORES", "AVENIDA DEL HIPODROMO", "ESTANCIA OJO DEL AGUA", "AVENIDA INDEPENDENCIA", "AVENIDA LOS PATAGONES", "232 - BO. V. DE LUJAN", "234 - BO. V. DE LUJAN", "B/P DON JOSE MOSCUZZA",
        "ANGEL PACHECO GENERAL", "EMILIO MARTIN LARRAYA", "CIUDAD DE BRAGADO BIS", "FEDERICO GARCIA LORCA", "FIGUEROA ALCORTA JOSE", "FLORENCIO PARRAVICINI", "GONZALEZ SEGURA CESAR", "DIAGONAL BORDE ARROYO",
        "DIAGONAL CESAR GASCON", "JACINTO PERALTA RAMOS", "JUANA MANUELA GORRITI", "JUAN BAUTISTA ALBERDI", "JUAN F. CZETZ CORONEL", "ESTANCIA LA PEREGRINA", "LAVALLE  JUAN GENERAL", "LOPEZ DE GOMARA JUSTO",
        "LOS COMECHINGONES SUR", "LOS EUCALIPTUS-BQ.P.R", "MARIANO CASTEX DOCTOR", "MARIO RAMON LUNA CABO", "MASCIAS ALBERTO ROQUE", "MAZZA SALVADOR DOCTOR", "OTTO KRAUSE INGENIERO", "QUINQUELLA MARTIN BIS",
        "RAMON CARRILLO DOCTOR", "RIVAS IGNACIO GENERAL", "SANCHEZ LABRADOR R.P.", "SAN FRANCISCO DE ASIS", "BARRAGAN-PJE HERMANAS", "CARLOS EDUARDO KRAUSE", "COBO-COLONIA BARRAGAN", "DE MARIA DAVID JEWETT",
        "AUGUSTO CESAR SANDINO", "JOSE GERVASIO ARTIGAS", "LIBERTADOR SAN MARTIN", "RAMIREZ  FRANCISCO J.", "AVENIDA JUAN B. JUSTO", "BOSCH MAYOL GUILLERMO", "JORGE NICOLAS POLITIS", "JORGE RODOLFO DIETSCH",
        "DOLORES MORA \"\"LOLA\"\"", "12 BIS - LA TRINIDAD", "CARMEN DE LAS FLORES", "CONSTANTINO GONZALEZ", "CRUCERO LA ARGENTINA", "DIAGONAL MAR AUSTRAL", "DIAGONAL SAN JACINTO", "DIARTE OSCAR SOLDADO",
        "DEL CABILDO INDIGENA", "CNO.A.LAS BRUSQUITAS", "HEGUILOR DOMINGO BIS", "JOSE ORTEGA Y GASSET", "ESTANCIA CHAPADMALAL", "ESTANCIA EL BOQUERON", "MANUEL QUERINI PADRE", "LA BRAVA - C. VERDES",
        "PESQUERO PALMA MADRE", "ESTANCIA LA COPELINA", "REMEDIOS DE ESCALADA", "REPUBLICA DEL LIBANO", "ARISTOBULO DEL VALLE", "ARTURO PEDRO LUISONI", "ARTURO PERALTA RAMOS", "DE LOS LOBOS MARINOS",
        "CENTRAL ISLA SOLEDAD", "AVENIDA CONSTITUCION", "JUAN B. JUSTO DOCTOR", "AVENIDA RIO COLORADO", "BERNARDO DE IRIGOYEN", "BOULEVARD DEL BOSQUE", "B/P DON TOMAS ROLDAN", "E. SAN ANTONIO ABATE",
        "B/P ESTRELLA DEL SUR", "AMALIA V. DE BALLINA", "EDUARDO PEREZ BULNES", "EMMA GEMOLI DE OLIVA", "ESCALADA REMEDIOS DE", "JOSE ANTONIO CABRERA", "JUAN FACUNDO QUIROGA", "ESTANISLAO DEL CAMPO",
        "LISANDRO DE LA TORRE", "MARTIN ALONSO PINZON", "MARTINIANO CHILABERT", "ORIGONE MANUEL FELIX", "PASAJE MAR DEL PLATA", "PEDRO Y TADEO FRANCO", "RAMBLA PUNTA MOGOTES", "ROLDAN BELISARIO BIS",
        "SAN FRANCISCO JAVIER", "SAN JOSE DE CALASANZ", "TORIBIO DE LUZURIAGA", "MARCELINO CHAMPAGNAT", "FEDERICO C. BELTRAMI", "LOS PADRES-V.SERRANA", "DANIEL ANTONIO JUKIC", "CRUCERO ARA BELGRANO",
        "JOSE LUIS DEL HIERRO", "JORGE ALBERTO LLAMAS", "ROCA JULIO ARGENTINO", "URQUIZA JUAN JOSE DE", "AVENIDA FERMIN ERREA", "VICTORIANO E. MONTES", "MARCELO T. DE ALVEAR", "CELSO NICANOR  ALDAO",
        "TRANSPORTE DE HORNOS", "83 - LOMAS DEL GOLF", "ALFREDO L. PALACIOS", "AMERICO RAUL CANOSA", "CARLOS MUJICA PADRE", "CNO.EA. LAS LOMITAS", "CNO. LIMITE NORESTE", "CNO.PIGS-J.B. JUSTO",
        "CNO.S.DE LOS PADRES", "COLECTORA NORTE VIA", "DESTRUCTOR HERCULES", "JUSTO ERNESTO ROMAN", "DIAGONAL LOS CURROS", "DIAGONAL PUEYRREDON", "TEODORO J. BRONZINI", "HOLMBERG EDUARDO L.",
        "HOUSSAY BERNARDO A.", "ESTANCIA LA REFORMA", "JOSE IGNACIO THAMES", "JOSE MANUEL ESTRADA", "ESTANCIA LA COLMENA", "MAMERTO ESQUIU FRAY", "PESQUERO HAPPY DAYS", "SANTIAGO DEL ESTERO",
        "ROMPE HIELOS IRIZAR", "ANTARTIDA ARGENTINA", "CENTENO NORBERTO O.", "FERMIN ERREA DOCTOR", "FRANCISCO QUINTEROS", "B/P SAN ANTONINO II", "AVENIDA SANTA MARTA", "BERUTI ANTONIO LUIS",
        "250 - BO. AUTODROMO", "BOULEVARD QUANTEMOC", "B/P LOS TRES AMIGOS", "663 (LOS CALAMARES)", "EVA DUARTE DE PERON", "FINOCHIETTO ENRIQUE", "FRANCISCO CHACAHUAC", "GUILLERMO VAN HEDEN",
        "ISLA DE LOS ESTADOS", "ISLAS TULES DEL SUR", "JOAQUIN V. GONZALEZ", "JUAN CARLOS DAVALOS", "ESTANCIA LA ARMONIA", "LOS CIPRECES-BQ.P.R", "LOS CLAVELES-BQ.P.R", "MACEDONIO FERNANDEZ",
        "MAC GAUL ANDRES BIS", "TERMAS DE RIO HONDO", "MARCELINO ECHEGARAY", "MIGUEL GUGLIELMOTTI", "MIGUEL SAGASTIZABAL", "PASAJE BANAT GABITO", "PASAJE SAN BERNARDO", "PSJE.BERUTI ANTONIO",
        "PLATA-BO. AUTODROMO", "CIRCUITO SAN MARTIN", "ENRIQUE FINOCHIETTO", "MARCELO JULIO FITTE", "BORDABEHERE SENADOR", "ESTANCIA CORRIENTES", "13 BIS-LA TRINIDAD", "1 - CNIA. BARRAGAN",
        "4 - CNIA. BARRAGAN", "CASTELLI JUAN JOSE", "CAYETANO RODRIGUEZ", "CEFERINO NAMUNCURA", "COMODORO RIVADAVIA", "CONRADO NALE ROXLO", "CORONEL SUAREZ BIS", "DE LOS ESPAÑOLES B",
        "DE LOS INMIGRANTES", "DE LOS RESERVISTAS", "CERRO SAN VALENTIN", "SANTA ROSA DEL MAR", "DIECKMANN JUANA G.", "CERVANTES SAAVEDRA", "HARAS LA MADRUGADA", "HECTOR BORDON CABO",
        "ESQUIVEL EMILIO J.", "ESTANCIA LA CORONA", "HEROES DE MALVINAS", "PESQUERO QUO VADIS", "REMOLCADOR GUARANI", "SANTIAGO CASABRUNA", "11 BIS-LA TRINIDAD", "AVELLANEDA NICOLAS",
        "AVENIDA JUAN CUTAY", "AVENIDA PEDRO LURO", "VICTORIO TETAMANTI", "BAUTISTA ALBERVIDE", "BAUTISTA MENDIOROZ", "VIRGEN DEL ROSARIO", "AMBROSETTI JUAN B.", "BORDEU JUAN MANUEL",
        "2 - CNIA. BARRAGAN", "3 - CNIA. BARRAGAN", "5 - CNIA. BARRAGAN", "9 -EST.CHAPADMALAL", "ALVARADO RUDECINDO", "ANGEL ROFFO DOCTOR", "ANTONIO A. VIGNOLO", "VUELTA DE OBLIGADO",
        "3 (GODOY CRUZ BIS)", "CHUYANTUYA CACIQUE", "CIANCHETTA LORENZO", "FRENGUELLI JOAQUIN", "GAMAL ABDEL NASSER", "GODOFREDO DAIREAUX", "JOSE ADRIAN BOTANA", "JOSE CARDIEL PADRE",
        "JOSÉ FERRARI OCAÑA", "JUAN A CASACUBERTA", "ESTANCIA ITUZAINGO", "JUAN NESTOR GUERRA", "ESTEBAN ECHEVERRIA", "LUIS VARETTO PADRE", "MAGRASSI GUILLERMO", "ONESIMO LEGUIZAMON",
        "OLEGARIO V ANDRADE", "PSJE.GARDEL CARLOS", "PEDRO MIGUEL ARAOZ", "VALENTIN SAYHUEQUE", "BRUSQUITAS-L BRAVA", "TROILO \"\"PICHUCO\"\"", "JUAN MARTIN ZABALA", "OMAR ALDO FERREYRA",
        "LA COLINA COMODORO", "ROLANDO PACHOLEZUK", "ANTONIO MARIA DIAZ", "MOSCONI ENRIQUE C.", "TESONE JUAN OTIMIO", "GRIERSON CECILIA A", "APARICIO FRANCISCO", "AGUSTIN RODRIGUEZ",
        "ALBERTO DEL SOLAR", "ALMONACID VICENTE", "9 -  COSTA ALEGRE", "CARLOS PELLEGRINI", "CATALINA DAPROTIS", "CATRIEL CIRPRIANO", "CNO.CNIA BARRAGAN", "CNO. CONSTITUCION",
        "CNO.URANGA HELMER", "COMUNA DE MAFALDA", "CONCEPCION ARENAL", "CORBETA GRANVILLE", "D´ARTAGNAN LOHIOL", "DE LA INMIGRACION", "DE LAS OLIMPIADAS", "DE LOS MISIONEROS",
        "DE LOS PEREGRINOS", "DE LOS PESCADORES", "DE MARCHI ANTONIO", "SANTANGELO INVADO", "DOLORES MEMBRIVES", "EDUARDO G. CARASA", "CIUDAD DE BRAGADO", "HARAS EL VENCEDOR",
        "HARAS LAS ORTIGAS", "HORACIO ENGLENDER", "GOYENECHE ROBERTO", "LUIS BELTRAN FRAY", "HIPOLITO BOUCHARD", "HELMER URANGA BIS", "MANUEL BAIGORRITA", "KRAGLIEVICH LUCAS",
        "REP. DE NICARAGUA", "REPUBLICA DE CUBA", "RICARDO GUIRALDES", "RICARDO GUTIERREZ", "JESUS DE GALINDEZ", "VICENTE LABORANTE", "ROSALIA DE CASTRO", "ANTONIO VALENTINI",
        "ARROYO CORRIENTES", "AVENIDA LAS TALAS", "BALTAZAR DEMATTEI", "BAUTISTA LAUREANO", "DON JOSE MOSCUZZA", "V.M.TERESA MICHEL", "BURMEISTER GERMAN", "54-BO.EL BOQUERON",
        "ALEJANDRO FLEMING", "ALVAREZ FRANCISCO", "B/P SAN FRANCISCO", "1 -  COSTA ALEGRE", "2 -  COSTA ALEGRE", "3 -  COSTA ALEGRE", "5 -  COSTA ALEGRE", "6 -  COSTA ALEGRE",
        "7 -  COSTA ALEGRE", "8 -  COSTA ALEGRE", "EL GALLEGO MANUEL", "EL MANUELIN TRUCO", "EL RUBIO FEDERICO", "EUSEBIONE LORENZO", "EVARISTO CARRIEGO", "EX CAMINO MIRAMAR",
        "CIUDAD DE DOLORES", "FERNANDO CATUOGNO", "FLORENCIO SANCHEZ", "CIUDAD DE ONEGLIA", "CIUDAD DE ROSARIO", "FLORISBELO ACOSTA", "FRAGATA MALDONADO", "FRAGATA SARMIENTO",
        "FRANCISCO ALVAREZ", "FRANCISCO PIZARRO", "FRANCISCO SARTORA", "FURLONG GUILLERMO", "GARAGIOLA ALBERTO", "GIACOMO MATTEOTTI", "GUERRICO ANATILDO", "CORTADA DEL TANGO",
        "JUANA AZURDUY BIS", "TOMAS ALVA EDISON", "JUAN N. FERNANDEZ", "LEOPOLDO MARECHAL", "HIPOLITO YRIGOYEN", "MATIENZO BENJAMIN", "MIGUEL DE UNAMUNO", "OLAZABAL FELIX DE",
        "PSJE.ERREA FERMIN", "PTA. RAMOS E. BIS", "PTA.RAMOS EDUARDO", "VILLARINO BASILIO", "SAAVEDRA CORNELIO", "GONZALEZ GUERRICO", "MARTIN BELLINZONA", "FELICIANO MALABIA",
        "HOZ FLORENCIO BIS", "CARLOS CASTAGNINO", "PIETRELCINA PADRE", "GUILLERMO SEVILLA", "ROSAS JUAN MANUEL", "PLAYA CHAPADMALAL", "SAVERIO SCARPATTI", "GUILLERMO MARCONI",
        "ALEJANDRO DACHARY", "ENRIQUE ANGELELLI", "MARIAS-L.DEL GOLF", "UNIVERSITARIA BIS", "PAUNERO WENCESLAO", "ACOSTA GOBERNADOR", "ZORZAL-BQ.P.RAMOS", "LOS LOBOS MARINOS",
        "ALBERT SCHWEITZER", "GUILLERMO FURLONG", "FITZERALD KENNEDY", "EUSEBIO COLOMBRES", "BAUTISTA AZOPARDO", "CONIQUEGUEN YAHAN", "COMECHINGONES SUR", "EUCALIPTUS-BQ.P.R",
        "AMBROSIO BESTOSO", "CAMET JUAN PEDRO", "CELEDONIO FLORES", "CELESTINO GALDOS", "CERRO CAMPANARIO", "DARREGUEYRA JOSE", "DE LOS ESPA?OLES", "DE LOS ITALIANOS",
        "DE LOS JUBILADOS", "DEL PUEBLO PAMPA", "LEOPOLDO LUGONES", "OVIDIO ZUBIAURRE", "CERRO MERCEDARIO", "DOMINGO HEGUILOR", "TEODORO BRONZINI", "HARAS FIRMAMENTO",
        "HARAS LA BIZNAGA", "HEGUILOR DOMINGO", "JOSE ROGER BALET", "LUIS ANGEL FIRPO", "PESQUERO KONTIKI", "PAULA ALBARRACIN", "SANTIAGO LACAMTU", "ROQUE SAENZ PEÑA",
        "10 - ARROYO SECO", "AVENIDA DIAGONAL", "JUAN HECTOR JARA", "AVENIDA LIBERTAD", "PRESIDENTE PERON", "VICTORIO FAGNANI", "BAUTISTA BALERDI", "BELISARIO ROLDAN",
        "BORDABEHERE ENZO", "DON TOMAS ROLDAN", "ESTRELLA DEL SUR", "B/P IVONNE MARTA", "54 - EL BOQUERON", "ALFONSINA STORNI", "ALBERTO EINSTEIN", "ALEJANDRO AGUADO",
        "ANTONIO SPINELLI", "ANTONIO STROPATO", "1 ( BELTRAN BIS)", "4 - COSTA ALEGRE", "TAYCHOCO CACIQUE", "CESAR A. CERETTI", "EL ZORRINO ROJAS", "ENRRIQUE LARRETA",
        "FEDERICO SERRANO", "FIGUEROA ALCORTA", "FRAGATA LIBERTAD", "FRANCISCO CANARO", "FRANCISCO FERRER", "GABRIELA MISTRAL", "GENARO GIACOBINI", "GERTRUDIS-BQ.P.R",
        "GRIERSON CECILIA", "INDIOS ARAUCANOS", "IRALA DOMINGO DE", "DIAGONAL CENTRAL", "ELPIDIO GONZALEZ", "JOAQUINA ACEVEDO", "JOSE DE LA LLOSA", "JOSE DUTTO PADRE",
        "ESTADO DE ISRAEL", "JUAN JOSE PEREDA", "LAS LAMBERCIANAS", "LAS LAMBERTIANAS", "LEBENSOHN MOISES", "LEONARDO ROSALES", "LORENZINI CAROLA", "HERMINIA BRUMANA",
        "HNOS FRASCAROLIO", "TIERRA DEL FUEGO", "MARTINEZ ANTONIO", "LAHILLE FERNANDO", "OSVALDO MAGNASCO", "PAJARITO PEREYRA", "PASAJE DE ANGELI", "PASCUAL MUGABURU",
        "PSJE.EL CARDENAL", "RODRIGUEZ MARTIN", "SALVADOR ALLENDE", "ROTONDA DEL LAGO", "TOMAS GODOY CRUZ", "TOMAS STEGAGNINI", "VALENTIN VERGARA", "WILLIAN C MORRIS",
        "GERONIMO CAMUSSO", "ABELARDO MOLTENI", "LOS DESAMPARADOS", "SANTOS DISCÉPOLO", "LAUREANO ESTEBAN", "MIGUEL DE ANDREA", "ANGEL CASTELLANO", "PADRES-V.SERRANA",
        "ALVAREZ CONDARCO", "GERVASIO ARTIGAS", "CABILDO INDIGENA", "LUIS PIEDRABUENA", "FERNANDEZ MORENO", "MARTIN JAURETCHE", "NUSDORFFER PADRE", "MARTINEZ GUSTAVO",
        "CACIQUE CANGAPOL", "JOSE MARIA PIRAN", "GRAL. PUEYRREDON", "HECTOR TARANTINO", "QUINQUELA MARTIN", "GUILLERMO BAYLEY", "ESTANISLAO SOLER", "VICENTE PEÑALOZA",
        "ENTRADA. GAZZOLO", "EST. CHAPADMALAL", "BAUTISTA ALBERDI", "MARIO RAMON LUNA", "FRANCISCO JAVIER", "-EST.CHAPADMALAL", "1 - ARROYO SECO", "67 - NUEVO GOLF",
        "ADOLFO E DAVILA", "AGUSTIN MAGALDI", "ALEJANDRO VOLTA", "CAMET FLORENCIO", "VIEJO A MIRAMAR", "SCAGLIA LORENZO", "CANDELARIA LUIS", "CANGAPOL-BQ.P.R",
        "CATULO CASTILLO", "SCIOCCO DOMINGO", "SEBASTIAN GARAU", "CNO.A LOS PATOS", "CERRO ACONCAGUA", "CORBETA URUGUAY", "COSTA ATLANTICA", "CRAMER AMBROSIO",
        "DAGLIO CAYETANO", "DANTE ALIGHIERI", "DE LA REDUCCION", "DE LAS CARRETAS", "DE LOS JESUITAS", "DE ROSAS JUAN M", "HORACIO QUIROGA", "EDUARDO BRADLEY",
        "CASTILLA Y LEON", "CERRO ACONQUIJA", "HARAS EL CANDIL", "HARAS HORIZONTE", "HARAS MALAL HUE", "HORACIO GAUDINI", "HUGO DEL CARRIL", "JOSE INGENIEROS",
        "JOSE LIJO LOPEZ", "LUIS DELLEPIANE", "MAIZANI AZUCENA", "MANUELA PEDRAZA", "PESQUERO HALCON", "PESQUERO NARWAL", "PESQUERO NOMADE", "PESQUERO PUMARA",
        "LOS CHIRIGUANOS", "SILVESTRE TOHEL", "RIO DE LA PLATA", "VICTORIA OCAMPO", "PDO. DE LOBERIA", "SANTIAGO CAYADO", "SANTIAGO DANERI", "SANTIAGO SASTRE",
        "TRINIDAD TOBAGO", "ASTOR PIAZZOLLA", "DE LA HERRADURA", "11 DE SETIEMBRE", "SAN ANTONINO II", "ROBERTO J PAYRO", "VIDAL CELESTINO", "AZUCENA MAIZANI",
        "VIGNOLO ANTONIO", "BENEDETTO CROCE", "20 DE SETIEMBRE", "VIRREY DEL PINO", "BORMIDA MARCELO", "LOS TRES AMIGOS", "B/P SAN GABRIEL", "BROWN ALMIRANTE",
        "CABO CORRIENTES", "CABRAL SARGENTO", "CALABRESE ENEAS", "6 - ARROYO SECO", "8 - ARROYO SECO", "ANDRES MAC GAUL", "ANGELONA PAGANO", "ANTONIO MACHADO",
        "CIOCCHINI CLETO", "GUTENBERG BIS B", "FELIPE DE ARANA", "FERNANDO BONNET", "CLEMENTE CAYROL", "FRESEDO OSVALDO", "GALEANA ANTONIO", "GONZALEZ CHAVEZ",
        "GREGORIO GOROZO", "INDA RUFINO BIS", "ISLA CANDELARIA", "ISLA CORONACION", "ISLA DE CERDEÑA", "JOSE DOCNOYAHAL", "JUAN JOSE VALLE", "LAS MADREPERLAS",
        "LAS TRES MARIAS", "LEANDRO N. ALEM", "LEONCIO CAMARGO", "LEOPOLDO MENDEZ", "LOS BAQUEANOS B", "LOS CRISANTEMOS", "ESTRELLA DE MAR", "MANUEL QUINTANA",
        "MARIQUE CACIQUE", "LA CRUZ DEL SUR", "MENGHIN EDUARDO", "MITRE BARTOLOME", "MONTE MALABRIGO", "NEWBERY EDUARDO", "OLEGARIO OLAZAR", "ORTIZ DE ZARATE",
        "OSVALDO FRESEDO", "PASAJE CATEDRAL", "PASAJE EL DANTE", "PSJE.EL HORNERO", "RAFAEL OBLIGADO", "RIO SAMBOROMBON", "SANTOS BAÑUELOS", "SACACHU CACIQUE",
        "TOMAS YEMEHUECH", "GUSTAVO MARQUEZ", "DE NORTEAMERICA", "GAUDINO DOCTORA", "JUANA FERNANDEZ", "VELEZ SARSFIELD", "DE CHAPEAUROUGE", "MONTES CARBALLO",
        "MAYOL GUILLERMO", "NICOLAS POLITIS", "RODOLFO DIETSCH", "JULIO ARGENTINO", "COLINA COMODORO", "NAVAL ARGENTINA", "FALCONIER MAYOR", "ESCOLLERA NORTE",
        "CELESTINO VIDAL", "MANUEL N. SAVIO", "RAFAEL DE RIEGO", "IGNACIO CORSINI", "HERMANN GMEINER", "ANTONIO ACEVEDO", "PLAZA FORTUNATO", "MANUELA GORRITI",
        "ANTONIO CABRERA", "FACUNDO QUIROGA", "(LOS CALAMARES)", "CIPRECES-BQ.P.R", "CLAVELES-BQ.P.R", "BIS-LA TRINIDAD", "LOS INMIGRANTES", "LOS RESERVISTAS",
        "13-LA TRINIDAD", "16-LA TRINIDAD", "CARLOS TEJEDOR", "CASILDO VILLAR", "CNO. EST. COBO", "CNO. RIO PINTO", "SERRANO JOSE M", "COSTA PAMPEANA",
        "CERRO FITZ ROY", "CRUZ DEL NORTE", "DE LA ENRAMADA", "DIAGONAL NORTE", "CERRO MURALLON", "DONATO ALVAREZ", "EDUARDO AROLAS", "SIERRA DE PUAN",
        "CERRO TRONADOR", "EDUARDO MALLEA", "CHANAL CACIQUE", "CERRO FIAMBALA", "CIUDAD DE ROMA", "GUTENBERG JUAN", "HARAS ABOLENGO", "HARAS ALFALFAR",
        "HARAS VOCACION", "JOSE LANZILOTA", "JOSE ZACAGNINI", "LOS TEHUELCHES", "PLACIDO GARCIA", "RIO MIRAFLORES", "ROCAS CORMORAN", "RICARDO BALBIN",
        "RINGUELET RAUL", "RIO CANDELARIA", "URQUIA SERAPIO", "B/P MARILUZ II", "ARMANDO CHULAK", "10-LA TRINIDAD", "11-LA TRINIDAD", "FELIX U. CAMET",
        "JUAN JOSE PASO", "12-LA TRINIDAD", "14-LA TRINIDAD", "15-LA TRINIDAD", "AVENIDA VERTIZ", "AYESA FELIX DE", "17-LA TRINIDAD", "BOMPLAND AMADO",
        "B/P CAMPANELLO", "CALABRIA BIS B", "11 - EL TREBOL", "VOLCAN COPAHUE", "ALFREDO LEPERA", "AGUSTIN VILERT", "ALBERTI MANUEL", "ALEJANDRO KORN",
        "14 - EL TREBOL", "ANGEL GARDELLA", "16 - EL TREBOL", "18 - EL TREBOL", "20 - EL TREBOL", "22 - EL TREBOL", "24 - EL TREBOL", "EL MIRADOR BIS",
        "EL MISO ZAMORA", "EL TANO TIZONE", "EMILIO SALGARI", "FELIX DE AYALA", "FERNANDEZ JUAN", "FRAGATA HALCON", "FRENCH DOMINGO", "FUNES GREGORIO",
        "GALLARDO ANGEL", "GANDHI MAHATMA", "GERONIMO REJON", "GOLETA SARANDI", "GRANJA MARUCHA", "ISLA DE BORBON", "ISLA DE ISCHIA", "ISLA JOINVILLE",
        "ISLA REMOLINOS", "ISLAS BALEARES", "JOSE DEYACOBBI", "JOSE GARIBALDI", "JOSE HERNANDEZ", "JUAN CALCHAQUI", "JUAN D`ARIENZO", "JUAN GUTENBERG",
        "LAS CASUARINAS", "LAS CORTADERAS", "LAS GALLARETAS", "LAS HORTENSIAS", "LAS MARAVILLAS", "LAS MARGARITAS", "LIBRES DEL SUR", "LOMAS DEL GOLF",
        "LOS ALGARROBOS", "ESTEBAN GASCON", "LOS DURAZNEROS", "LOS EUCALIPTOS", "LOS EUCALIPTUS", "LOS HIPOCAMPOS", "LOS MEJILLONES", "LOS QUEBRACHOS",
        "LOS QUERANDÍES", "HNOS ALDACOCHE", "MACACHA GUEMES", "JULIAN AGUIRRE", "JULIO CORTAZAR", "MATHEU DOMINGO", "MATIAS STROBEL", "MIGUEL URRUTIA",
        "MIGUEL VIGNOLO", "PARODI LORENZO", "PASAJE EL FARO", "PASCANA GRANDE", "PSJE.EL ZORZAL", "PSJE. PORTUGAL", "PSJE.VENEZUELA", "RAMON ITURRIOZ",
        "PEDRO IRIGOYEN", "RODRIGUEZ PEÑA", "ROMERO EDUARDO", "SOUESSIA ISAAC", "SUAREZ CORONEL", "VECINOS UNIDOS", "VELEZ GREGORIO", "HUMBERTO ILLIA",
        "LIMITE NORESTE", "ENRIQUE HUDSON", "EDUARDO RACEDO", "MARIO GURRIERE", "MARCELO PLANES", "EDUARDO KRAUSE", "HIERRO SOLDADO", "ALBERTO LLAMAS",
        "NOROESTE NORTE", "ISLAS MALVINAS", "DE SCHOENSTATT", "AMAYA DIPUTADO", "MARIA REMEDIOS", "LAS FLORES BIS", "ERNESTO SEGURA", "JOSE M. CALAZA",
        "JOSE RODRIGUEZ", "MARIA GIANELLI", "FEDERICO RAUCH", "JERONIMO COSTA", "DIOS FILIBERTO", "JUAN MADARIAGA", "LICIO MANSILLA", "HORNERO-BQ.P.R",
        "PAZ JOSE MARIA", "SAAVEDRA LAMAS", "LOS PESCADORES", "MARTIN LARRAYA", "MARIANO CASTEX", "MAZZA SALVADOR", "RAMON CARRILLO", "IGNACIO THAMES",
        "MANUEL ESTRADA", "CARLOS DAVALOS", "CNIA. BARRAGAN", "LA INMIGRACION", "LAS OLIMPIADAS", "LOS MISIONEROS", "LOS PEREGRINOS", "MARCHI ANTONIO",
        "GALLEGO MANUEL", "MANUELIN TRUCO", "RUBIO FEDERICO", "CAMINO MIRAMAR", "ELIAS ANTUNEZ", "3-LA TRINIDAD", "7-LA TRINIDAD", "9-LA TRINIDAD",
        "CARLOS GARDEL", "CARLOS PIGOZI", "CNO.EL TEJADO", "CNO.EST CAMET", "CNO.STA PAULA", "COMECHINGONES", "CERRO HERMOSO", "CURA BROCHERO",
        "DEL CORRALERO", "MANUEL CANATA", "MAR DEL PLATA", "DIAGONAL OMBU", "RENE FAVALORO", "SANTA CECILIA", "DOMINGO BATAN", "EA. SAN JUSTO",
        "CHILABERT BIS", "HAENCKE TADEO", "HARAS COMALAL", "HARAS EL TURF", "ATLANTICO SUR", "LAS NAZARENAS", "HERNAN CORTES", "LOS TULIPANES",
        "LUCIANO ARRUE", "HELMER URANGA", "MANUEL BLANCO", "MANUEL GRANDE", "LA GOLONDRINA", "GUTENBERG BIS", "LOS CHIMANGOS", "LOS CARRUAJES",
        "REGION MOLISE", "REPUBLIQUETAS", "RICARDO PALMA", "RICARDO ROJAS", "RIO CALCHAQUI", "RIO CARCARAÑA", "RIO CORCOVADO", "RIO FELICIANO",
        "RIO GUALEGUAY", "RIO LAS LAJAS", "HIPOLITO SOSA", "PEDRO BOUCHEZ", "PEDRO DEJORGE", "VICENTE LOPEZ", "VILLA GUSTAVA", "ARANA Y GOIRI",
        "AVENIDA COLON", "DEL HIPODROMO", "INDEPENDENCIA", "12 DE OCTUBRE", "LOS PATAGONES", "VIOLETA PARRA", "BENITO JUAREZ", "1-LA TRINIDAD",
        "BORTHABURU A.", "ABDALA GERMAN", "5-LA TRINIDAD", "CABRERA ANGEL", "6-LA TRINIDAD", "8-LA TRINIDAD", "AMADEO COUREL", "ANTONIO ALICE",
        "ANTONIO SAENZ", "SAN FRANCISCO", "1 - EL TREBOL", "TAVELLI PABLO", "TAPIA AUGUSTO", "LA PASIONARIA", "7 - EL TREBOL", "8 - EL TREBOL",
        "EDUARDO WILDE", "EL CARPINTERO", "EL CHURRINCHE", "EL EMPRENDADO", "EUSEBIO BLANC", "FAUSTINO NUÑO", "FRAGATA ITATI", "GARAY JUAN DE",
        "GO?I JUAN BIS", "GROEBER PABLO", "BOSQUE GRANDE", "ISLA ELEFANTE", "ISLA SEBALDES", "ISLA TRAVERSE", "ISLA TRINIDAD", "JORGE CAFRUNE",
        "JUANA AZURDUY", "JUAN FERMINIA", "JUAN JAUREGUI", "JUAN VUCETICH", "LAS CABRILLAS", "LAS CARACOLAS", "LAS CENTOLLAS", "LAS GARDENIAS",
        "LAS GROSELLAS", "LAS MAGNOLIAS", "LAS PALOMETAS", "LAS TIJERETAS", "LEON FRAGNAUD", "LOS ALMENDROS", "LOS ARRAYANES", "LOS AVELLANOS",
        "LOS BAQUEANOS", "LOS CALAMARES", "LOS DIAGUITAS", "LOS GLADIOLOS", "LOS GUARANIES", "LOS INCIENSOS", "LOS LIMONEROS", "LOS MOHICANOS",
        "LOS PALENQUES", "LOS RANQUELES", "LUIS SANDRINI", "JULIO CANESSA", "JULIO DE CARO", "MARCOS SASTRE", "MARIANO ROSAS", "MARTIN FIERRO",
        "MARTIN OVIEDO", "TIERRA GAUCHA", "MORENO PERITO", "MOYANO CARLOS", "NICOLAS DAZEO", "PRIMERA JUNTA", "PSJE. ECUADOR", "PUERTO MADRYN",
        "RAFAEL GARCIA", "RAMON CABEZAS", "RIO PILCOMAYO", "RIO TUPUNGATO", "RODOLFO WALSH", "PEDRO FERRARI", "PEDRO GUILLEN", "PEDRO MEDRANO",
        "ROMANO NESTOR", "SALVADOR VIVA", "TOMAS FALKNER", "VICENTE CUELI", "PEDRO EDUARDO", "DELLA PAOLERA", "NICANOR ALDAO", "LA CONCEPCION",
        "EA. ITUZAINGO", "PERALTA RAMOS", "MARQUEZ RAMON", "CASTRO BARROS", "MANUEL FANGIO", "ANTONIO JUKIC", "DE BUSTAMANTE", "CESAR SANDINO",
        "FLORENCIO BIS", "ERNESTO ROMAN", "DE JOVELLANOS", "VERA Y ARAGON", "MARTIN ZABALA", "ALVEAR DOCTOR", "ALDO FERREYRA", "LOBOS MARINOS",
        "AVENIDA PERON", "ANTONIO ABATE", "MORA \"\"LOLA\"\"", "ANGEL RIZZUTO", "RIEGO GENERAL", "MARTINEZ BAYA", "ANGEL BONANNI", "PETERSEN JUAN",
        "UNIVERSITARIA", "JOSE MOSCUZZA", "ANGEL PACHECO", "JUAN F. CZETZ", "LAVALLE  JUAN", "ALBERTO ROQUE", "RIVAS IGNACIO", "LABRADOR R.P.",
        "QUERINI PADRE", "PEDRO LUISONI", "JUAN B. JUSTO", "ALONSO PINZON", "PUNTA MOGOTES", "BELISARIO BIS", "HIELOS IRIZAR", "BO. AUTODROMO",
        "HECTOR BORDON", "ADRIAN BOTANA", "CARDIEL PADRE", "FERRARI OCAÑA", "A CASACUBERTA", "NESTOR GUERRA", "VARETTO PADRE", "LOS ESPA?OLES",
        "LOS ITALIANOS", "LOS JUBILADOS", "ZORRINO ROJAS", "CARLOS BERRA", "CARLOS MELGA", "CNO.EL CASAL", "CNO.EST COBO", "CERRO FATIMA",
        "DE LOS INCAS", "HOMERO MANZI", "JOSE PEDRONI", "PLAYA SERENA", "CERRO NEVADO", "DIAGONAL SUR", "IGNACIO OLAN", "JOSE RAZZANO",
        "HERNANDARIAS", "LOS ZORZALES", "LUCIO VARELA", "LUIS DEL ORO", "LA CALANDRIA", "LOS CHAÑARES", "LOS CIPRECES", "LOS CASTAÑOS",
        "RIO CEBALLOS", "RIO GALLEGOS", "SAN PATRICIO", "SAN SALVADOR", "TRES ARROYOS", "AVENIDA ABEL", "CONSTITUCION", "RIO COLORADO",
        "BAHIA BLANCA", "BAHÍA THETIS", "VIÑA DEL MAR", "BENITO LINCH", "NUEVO BOSQUE", "IVONNE MARTA", "BUENOS AIRES", "3 DE FEBRERO",
        "CALABRIA BIS", "CALASANZ BIS", "EL AMERICANO", "EL CORBATITA", "ELIAS ALIPPI", "EL MANANTIAL", "EL MANGRULLO", "EL TERU TERU",
        "GERTRUDIS M.", "BORDE ARROYO", "ISLA PAJAROS", "ISLA SOLEDAD", "CESAR GASCON", "JORGE AVALOS", "JUAN A. PEÑA", "JUAN B. GOÑI",
        "JUAN LABORDE", "JUAN MARIANI", "LA MARTINETA", "LA PRIMAVERA", "LA QUERENCIA", "LAS ALAMEDAS", "LAS AZUCENAS", "LAS BALLENAS",
        "LAS CAMELIAS", "LAS CHARITAS", "LAS CORVINAS", "LAS HIGUERAS", "LAS PALMERAS", "LAS TORTUGAS", "LAS VIOLETAS", "LA TORCACITA",
        "LOS ABEDULES", "LOS ABIPONES", "LOS ARENQUES", "LOS ARRIEROS", "LOS CANDILES", "LOS CARDALES", "LOS CIRUELOS", "LOS CLAVELES",
        "LOS DELFINES", "LOS GERANIOS", "LOS GRANADOS", "LOS HALCONES", "LOS HELECHOS", "LOS JACINTOS", "LOS JAZMINES", "LOS MALVONES",
        "LOS MANZANOS", "LOS MAPUCHES", "LOS MINUANES", "LOS MOCORETA", "LOS NARANJOS", "LOS NARVALES", "LOS NAUTILUS", "LOS OLIVARES",
        "LOS PARAISOS", "LOS PEÑASCOS", "LOS PLATANOS", "LOS PLATEROS", "LOS SALMONES", "LUIS VARESSE", "MONTE OLIVIA", "NAHUEL HUAPI",
        "PABLO NERUDA", "PURA SAGASTA", "QUESADA JOSE", "RAFAEL LATUF", "ROBERTO ARLT", "PEDRO GOYENA", "SOLER MIGUEL", "STELLA MARIS",
        "SAGASTA PURA", "R. CHAVERO\"\"", "TAPERA NORTE", "NORTEAMERICA", "DESAMPARADOS", "CHAPEAUROUGE", "LAS HERMANAS", "EL SOLITARIO",
        "DAVID JEWETT", "FRANCISCO J.", "ARA BELGRANO", "LA PELEGRINA", "FERMIN ERREA", "LAS LAGRIMAS", "DE ANCHORENA", "DEL FOURNIER",
        "LA HERRADURA", "DE MEYRELLES", "DAVID ORTEGA", "BAHIA THETIS", "LOS DIFUNTOS", "JULIO RATERY", "DE SUDAFRICA", "SAN CAYETANO",
        "SAN CIPRIANO", "GARCIA LORCA", "ALCORTA JOSE", "SEGURA CESAR", "LA PEREGRINA", "GOMARA JUSTO", "LA ARGENTINA", "DIARTE OSCAR",
        "TOMAS ROLDAN", "PEREZ BULNES", "MANUEL FELIX", "TADEO FRANCO", "DE LUZURIAGA", "MUJICA PADRE", "ANTONIO LUIS", "GUGLIELMOTTI",
        "SAGASTIZABAL", "BANAT GABITO", "SAN BERNARDO", "SAN VALENTIN", "LA MADRUGADA", "ABDEL NASSER", "MIGUEL ARAOZ", "COSTA ALEGRE",
        "BELTRAN FRAY", "DE NICARAGUA", "N. FERNANDEZ", "PUEBLO PAMPA", "BELTRAN BIS)", "LAMBERCIANAS", "LAMBERTIANAS", "LA REDUCCION",
        "LAS CARRETAS", "LOS JESUITAS", "DE SETIEMBRE", "128 - BATAN", "22 DE ABRIL", "AGUA BLANCA", "SICILIA BIS", "CNO.MARAYUI",
        "CERRO ADELA", "DARDO ROCHA", "SEVERO RUIZ", "MAR AUSTRAL", "SAN JACINTO", "CERRO PAINE", "CERRO LANIN", "CERRO TORRE",
        "JOSE MARMOL", "JOSE PANTEA", "JOSE YAHATY", "LOS TILOS B", "LUIS FRANCO", "LUIS LELOIR", "MANCU COPAC", "JULIAN RIOS",
        "JULIO VERNE", "LOS CEREZOS", "RIO MATANZA", "RIO AGUAPEY", "RIO BERMEJO", "RIO COSQUIN", "SAN LORENZO", "SANTA ELENA",
        "TRIUNVIRATO", "TUPAC-AMARU", "BLAS PARERA", "ARTURO ALIO", "AVALOS JUAN", "B/P PAMPERO", "AVENIDA LIA", "B/P PIONERO",
        "14 DE JULIO", "SANTA MARTA", "BOSCH ELISA", "B/P DORREGO", "SAN GABRIEL", "BRAVO MARIO", "CALCHAQUIES", "EL BENTEVEO",
        "EL CENCERRO", "EL CHINGOLO", "EL COLMENAR", "EL FLAMENCO", "EL GAVIOTIN", "CHAPADMALAL", "EL JILGUERO", "EL LEÑATERO",
        "EL PEJERREY", "EL PICAFLOR", "EL PIRINCHO", "EL TORDILLO", "FERRE PEDRO", "GUIDO TOMAS", "ISLA BLANCO", "ISLA LAURIE",
        "JOSE ALONSO", "JUANA MANSO", "LA QUEBRADA", "LA RATONERA", "LAS ACACIAS", "LAS ALMEJAS", "LAS AZALEAS", "LAS ENCINAS",
        "LA SERRANIA", "LAS FRECIAS", "LAS MORERAS", "LAS NUTRIAS", "LAS RETAMAS", "LAS TONINAS", "LAS TOTORAS", "LA TIJERETA",
        "LA TROPILLA", "LOS ALELIES", "LOS AZTECAS", "LOS CORALES", "LOS FOGONES", "LOS FRESNOS", "LOS MATACOS", "LOS MIMBRES",
        "LOS NOGALES", "LOS PERALES", "LOS QUILMES", "LUIS VERNET", "JULIO MUÑOZ", "LA CACHIRLA", "MARIE CURIE", "MARIO BRAVO",
        "MIGUEL CANE", "OUTES FELIX", "PABON PEDRO", "RAMON ARVES", "RIO TERCERO", "PEDRO FERRE", "SAN ANTONIO", "SANAVIRONES",
        "RUBEN DARIO", "VALLE VERDE", "VAN HEDEN G", "YAHATY JUAN", "ZANNI PEDRO", "MAR PRIMERA", "ENRIQUE RAU", "ITUZAINGO B",
        "DE VIVORATA", "LOS ESTADOS", "C. BELTRAMI", "EL SALVADOR", "BORDEU JUAN", "NORBERTO O.", "JUAN MANUEL", "PIEDRABUENA",
        "FINOCHIETTO", "JULIO FITTE", "SCHOENSTATT", "JUAN OTIMIO", "MARIA PIRAN", "HECTOR JARA", "DE GALINDEZ", "SANTA CLARA",
        "S. ZEBALLOS", "RUFINO INDA", "ARABE SIRIA", "BRAGADO BIS", "PARRAVICINI", "OTTO KRAUSE", "LA TRINIDAD", "DOMINGO BIS",
        "EL BOQUERON", "PALMA MADRE", "LA COPELINA", "DE ESCALADA", "DE IRIGOYEN", "REMEDIOS DE", "DE CALASANZ", "L. PALACIOS",
        "RAUL CANOSA", "LAS LOMITAS", "J. BRONZINI", "BERNARDO A.", "ESQUIU FRAY", "ANTONINO II", "TRES AMIGOS", "V. GONZALEZ",
        "ESPAÑOLES B", "INMIGRANTES", "RESERVISTAS", "DE MALVINAS", "DEL ROSARIO", "ANGEL ROFFO", "DE OBLIGADO", "CASACUBERTA",
        "INMIGRACION", "EL VENCEDOR", "LAS ORTIGAS", "AZURDUY BIS", "ALVA EDISON", "ROGER BALET", "ANGEL FIRPO", "ARROYO SECO",
        "DUTTO PADRE", "JOSE PEREDA", "FRASCAROLIO", "CHIRIGUANOS", "MADREPERLAS", "TRES MARIAS", "BAQUEANOS B", "CRISANTEMOS",
        "SAMBOROMBON", "LA ENRAMADA", "MIRADOR BIS", "MISO ZAMORA", "TANO TIZONE", "CAMPESINOS", "CAMPO FLOR", "CANAI QUEN",
        "ARQ.CEDRON", "CAUPOLICAN", "CEDRO AZUL", "CERRO AZUL", "CORRIENTES", "COSTA AZUL", "CURRUNAHEL", "DEL ALJIBE",
        "DEL LUCERO", "LOS CURROS", "PUEYRREDON", "DON ORIONE", "HNOS SMITH", "JOSE MARTI", "LUIS AGOTE", "PESCADORES",
        "PLUS ULTRA", "LOS CEIBOS", "RIO BLANCO", "RIO CURACO", "RIO JACHAL", "SAN MARTIN", "SANTA CRUZ", "SANTA INES",
        "SANTA ROSA", "MARILUZ II", "B/P MARLIN", "JUAN CUTAY", "PEDRO LURO", "DEL BOSQUE", "B/P ALTAIR", "CAMPANELLO",
        "B/P FOCA B", "25 DE MAYO", "CALAZA BIS", "9 DE JULIO", "ALMAFUERTE", "EL ESTRIBO", "EL GORRION", "EL HORNERO",
        "CHAMPAGNAT", "EL MILAGRO", "EL MIRADOR", "EL PAMPERO", "EL REMANSO", "EL ROSILLO", "EL TAJAMAR", "EL TOBIANO",
        "ENTRE RIOS", "GENOVA BIS", "GOLONDRINA", "GUAYCURUES", "ISLA VIGIA", "LAS DALIAS", "LA SERRANA", "LAS FRESAS",
        "LAS OSTRAS", "LA TORCAZA", "LA VAGUADA", "LA VIHUELA", "LILLO LUIS", "LOS ABETOS", "LOS ALAMOS", "LOS APEROS",
        "LOS AROMOS", "LOS JUNCOS", "LOS LIRIOS", "LOS MIRLOS", "LOS NARDOS", "LOS OMBUES", "LOS ROBLES", "LOS SAUCES",
        "MAGALLANES", "LA ALONDRA", "LA CIGUEÑA", "LA GAVIOTA", "MIGUELETES", "NEWBERY J.", "PAGO CHICO", "LOS CEDROS",
        "PUJIA JOSE", "RIO NOGOYA", "RIO PARANA", "RIO SUQUIA", "ROCA JULIO", "SAN BENITO", "TALCAHUANO", "YANQUETRUZ",
        "YAPEYU BIS", "- OTAMENDI", "BELLINZONA", "CONCEPCION", "A AEROCLUB", "CASTELLANO", "BUSTAMANTE", "LOS PADRES",
        "CASTAGNINO", "EL COYUNCO", "LA REFORMA", "DEL HIERRO", "JOVELLANOS", "STA ISABEL", "\"PICHUCO\"\"", "EL SOSIEGO",
        "DE NAVARRA", "PACHOLEZUK", "MARIA DIAZ", "ENRIQUE C.", "GOBERNADOR", "SCHWEITZER", "FLORES BIS", "Y ANGELITO",
        "RIO IGUAZU", "DE CALCUTA", "HOZ MIGUEL", "JOSE MARIA", "RAMON LUNA", "MARTIN BIS", "LAS FLORES", "BRUSQUITAS",
        "DEL LIBANO", "DE BALLINA", "EDUARDO L.", "LA COLMENA", "HAPPY DAYS", "DEL ESTERO", "CALAMARES)", "LA ARMONIA",
        "ANDRES BIS", "NALE ROXLO", "SUAREZ BIS", "A. VIGNOLO", "ECHEVERRIA", "LEGUIZAMON", "PELLEGRINI", "DE MAFALDA",
        "OLIMPIADAS", "MISIONEROS", "PEREGRINOS", "DE BRAGADO", "URANGA BIS", "BAIGORRITA", "DE DOLORES", "DE ONEGLIA",
        "DE ROSARIO", "DE UNAMUNO", "JUAN PEDRO", "CAMPANARIO", "MERCEDARIO", "FIRMAMENTO", "LA BIZNAGA", "ALBARRACIN",
        "SAENZ PEÑA", "A. CERETTI", "DOMINGO DE", "GODOY CRUZ", "STEGAGNINI", "NUEVO GOLF", "DEL CARRIL", "LIJO LOPEZ",
        "DELLEPIANE", "DE LOBERIA", "RUFINO BIS", "CANDELARIA", "CORONACION", "DE CERDEÑA", "DOCNOYAHAL", "JOSE VALLE",
        "TEHUELCHES", "MIRAFLORES", "CASUARINAS", "CORTADERAS", "GALLARETAS", "HORTENSIAS", "MARAVILLAS", "MARGARITAS",
        "ALGARROBOS", "DURAZNEROS", "EUCALIPTOS", "EUCALIPTUS", "HIPOCAMPOS", "MEJILLONES", "QUEBRACHOS", "QUERANDÍES",
        "DE OCTUBRE", "PASIONARIA", "CARPINTERO", "CHURRINCHE", "EMPRENDADO", "DE FEBRERO", "SEMBRADOR", "CATAMARCA",
        "COLECTORA", "DEL TEJAR", "DON BOSCO", "LOS TILOS", "JURAMENTO", "LA AGUADA", "LA LAGUNA", "RAUCH BIS",
        "PATAGONES", "RIO ATUEL", "RIO BELEN", "RIO DULCE", "PATAGONIA", "SAN PEDRO", "VALENTINA", "ARAUCANOS",
        "ARGENTINA", "ARRIBE?OS", "ATAHUALPA", "LAS TALAS", "AZCUENAGA", "1 DE MAYO", "QUANTEMOC", "CALFUCURA",
        "120 BATAN", "EL ALAZAN", "EL HORCON", "CHACABUCO", "EL JAGUEL", "EL RECADO", "EL RINCON", "EL TEJADO",
        "EL ZORZAL", "FLORENCIA", "FLORENCIO", "FRANCISCA", "FRANCISCO", "GERTRUDIS", "GO?I JUAN", "GUANAHANI",
        "GUILLERMO", "INCA HUEN", "ITUZAINGO", "JUAN ACHA", "LA PERDIZ", "LA LOMADA", "LA MATERA", "LAS CALAS",
        "LAS FOCAS", "LAS HAYAS", "LAS HERAS", "LAS LISAS", "LAS LOMAS", "LAS ORCAS", "LAS ROSAS", "LA SURE?A",
        "LOMBARDIA", "LOS ARCES", "LOS INCAS", "RIO LIMAY", "LOS OLMOS", "LOS ORTIZ", "LOS PINOS", "LOS TAPES",
        "LA AURORA", "MARGARITA", "ORO NEGRO", "RIO LULES", "LA COLINA", "LA CUESTA", "MOCTEZUMA", "NAHUELPAN",
        "NAMUNCURA", "NATIVIDAD", "O'HIGGINS", "OLAVARRIA", "PALESTINA", "RIO NEGRO", "RIO PINTO", "RIO TEUCO",
        "RIVADAVIA", "SARMIENTO", "VENEZUELA", "CHAVERO\"\"", "GAUDINO A", "FERNANDEZ", "DEL PILAR", "SARSFIELD",
        "DISCÉPOLO", "DE ANDREA", "COYUNCO B", "ESPERANTO", "SOLITARIO", "AUTODROMO", "DE MILLAN", "ARGENTINO",
        "PELEGRINA", "QUINTEROS", "E. MONTES", "SCARPATTI", "DE ALVEAR", "TETAMANTI", "ANGELELLI", "DEL TANGO",
        "EL RETAZO", "ZUBIAURRE", "WENCESLAO", "DE HORNOS", "JAURETCHE", "ANCHORENA", "STA CLARA", "DE GOMARA",
        "HERRADURA", "DE VIEDMA", "CECILIA A", "MEYRELLES", "TARANTINO", "DE GUEMES", "BO. CAMET", "A MIRAMAR",
        "DEL PLATA", "M. CALAZA", "RODRIGUEZ", "SUDAFRICA", "JOSE PASO", "COLOMBRES", "FILIBERTO", "MADARIAGA",
        "FORTUNATO", "HIPODROMO", "PEREGRINA", "C. VERDES", "DEL VALLE", "DEL CAMPO", "CHILABERT", "LUZURIAGA",
        "NORTE VIA", "CHACAHUAC", "VAN HEDEN", "RIO HONDO", "ECHEGARAY", "JUAN JOSE", "MADRUGADA", "EMILIO J.",
        "LA CORONA", "QUO VADIS", "CASABRUNA", "ALBERVIDE", "MENDIOROZ", "RUDECINDO", "CRUZ BIS)", "V ANDRADE",
        "SAYHUEQUE", "DEL SOLAR", "CIRPRIANO", "GRANVILLE", "MEMBRIVES", "G. CARASA", "ENGLENDER", "NICARAGUA",
        "GUIRALDES", "GUTIERREZ", "LABORANTE", "DE CASTRO", "VALENTINI", "MALDONADO", "MATTEOTTI", "ESPA?OLES",
        "ITALIANOS", "JUBILADOS", "GIACOBINI", "DE ISRAEL", "DEL FUEGO", "DE ANGELI", "LOS PATOS", "ACONCAGUA",
        "ATLANTICA", "ALIGHIERI", "REDUCCION", "ACONQUIJA", "EL CANDIL", "HORIZONTE", "MALAL HUE", "PIAZZOLLA",
        "CELESTINO", "ALMIRANTE", "BARTOLOME", "MALABRIGO", "DE ZARATE", "YEMEHUECH", "EST. COBO", "DEL NORTE",
        "LANZILOTA", "ZACAGNINI", "EL TREBOL", "DE BORBON", "DE ISCHIA", "JOINVILLE", "REMOLINOS", "DEYACOBBI",
        "GARIBALDI", "HERNANDEZ", "CALCHAQUI", "D`ARIENZO", "GUTENBERG", "ALDACOCHE", "CORRALERO", "SAN JUSTO",
        "NAZARENAS", "TULIPANES", "CHIMANGOS", "CARRUAJES", "CARCARAÑA", "CORCOVADO", "FELICIANO", "GUALEGUAY",
        "LAS LAJAS", "CABRILLAS", "CARACOLAS", "CENTOLLAS", "GARDENIAS", "GROSELLAS", "MAGNOLIAS", "PALOMETAS",
        "TIJERETAS", "ALMENDROS", "ARRAYANES", "AVELLANOS", "BAQUEANOS", "CALAMARES", "DIAGUITAS", "GLADIOLOS",
        "GUARANIES", "INCIENSOS", "LIMONEROS", "MOHICANOS", "PALENQUES", "RANQUELES", "PILCOMAYO", "TUPUNGATO",
        "CALANDRIA", "AMERICANO", "CORBATITA", "MANANTIAL", "MANGRULLO", "TERU TERU", "MARTINETA", "PRIMAVERA",
        "QUERENCIA", "TORCACITA", "AGUATERO", "AMEGHINO", "CANGAPOL", "CARDENAL", "CATALUÑA", "CNO.PIGS",
        "COLIQUEO", "COLOMBIA", "EL VALLE", "DIAGONAL", "CHARLONE", "CHARRUAS", "CHINGOLO", "EL ZAINO",
        "HERRERIA", "MALVINAS", "MANSILLA", "LA BRAVA", "PEUMAYEN", "PORTUGAL", "PRAXEDES", "RIO MAYO",
        "PATRICIA", "SANTA FE", "SAN LUIS", "ARENALES", "ASTURIAS", "LIBERTAD", "VICTORIA", "AYACUCHO",
        "BALCARCE", "BAUTISTA", "VIRGINIA", "BELGRANO", "BELL MAR", "B/P FOCA", "BRANDSEN", "CALABRIA",
        "39 BIS B", "EL CERRO", "EL CHAJA", "EL MATEO", "EL MIXTO", "EL MONTE", "EL RODEO", "EL SULKY",
        "EL TORDO", "ESC. SUR", "CIPRESES", "EVARISTO", "FAUSTINO", "GRACIELA", "GREGORIO", "GUERNICA",
        "JOSEFINA", "LA POSTA", "LAMADRID", "LA PAMPA", "LA RIOJA", "LITUANIA", "LOS TALA", "LABARDEN",
        "MENENDEZ", "MERCEDES", "MISIONES", "MOCOBIES", "MONSALVO", "LA LAURA", "LA LEGUA", "NECOCHEA",
        "NOGUEIRA", "NORBERTO", "PARAGUAY", "PRINGLES", "PUCO YAN", "PUELCHES", "SAN JUAN", "RUMEN CO",
        "VALENCIA", "VERONICA", "VIAMONTE", "GUERRICO", "OTAMENDI", "VIVORATA", "HERMANAS", "AEROCLUB",
        "GURRIERE", "CARBALLO", "BELTRAMI", "BARRAGAN", "DEL AGUA", "SALVADOR", "CONDARCO", "B. JUSTO",
        "Y ARAGON", "INDIGENA", "DEL GOLF", "FERREYRA", "COMODORO", "JUAN BIS", "AL NORTE", "LAGRIMAS",
        "SAN BLAS", "GONZALEZ", "LA SALLE", "DIPUTADO", "- BQ.P.R", "EST COBO", "REMEDIOS", "FOURNIER",
        "N. SAVIO", "ANGELITO", "GALINDEZ", "DE JUNCO", "DE RIEGO", "PEÑALOZA", "DIFUNTOS", "FAVALORO",
        "Y PLANES", "U. CAMET", "DE JUSTO", "MARIA DE", "GIANELLI", "DE BOSCH", "CAYETANO", "DE LOPEZ",
        "AZOPARDO", "ZEBALLOS", "LA BOMBA", "CIPRIANO", "DE LUJAN", "MOSCUZZA", "F. CZETZ", "CARRILLO",
        "TRINIDAD", "Y GASSET", "BOQUERON", "COPELINA", "ESCALADA", "COLORADO", "IRIGOYEN", "DE OLIVA",
        "LA TORRE", "CALASANZ", "PALACIOS", "HERCULES", "BRONZINI", "DE PERON", "BERNARDO", "VALENTIN",
        "JUANA G.", "SAAVEDRA", "OBLIGADO", "DAIREAUX", "DAPROTIS", "VENCEDOR", "BOUCHARD", "DEMATTEI",
        "LAUREANO", "FEDERICO", "CARRIEGO", "CATUOGNO", "ANATILDO", "MARECHAL", "YRIGOYEN", "BENJAMIN",
        "FELIX DE", "CORNELIO", "HEGUILOR", "EINSTEIN", "SPINELLI", "STROPATO", "LA LLOSA", "FERNANDO",
        "MAGNASCO", "MUGABURU", "DEL LAGO", "C MORRIS", "E DAVILA", "CASTILLO", "AMBROSIO", "CARRETAS",
        "JESUITAS", "LA PLATA", "DEL PINO", "MAC GAUL", "DE ARANA", "QUINTANA", "CATEDRAL", "EL DANTE",
        "BAÑUELOS", "PAMPEANA", "FITZ ROY", "ENRAMADA", "MURALLON", "TRONADOR", "FIAMBALA", "ABOLENGO",
        "ALFALFAR", "VOCACION", "CORMORAN", "GARDELLA", "DE AYALA", "BALEARES", "CORTAZAR", "ITURRIOZ",
        "BROCHERO", "ELEFANTE", "SEBALDES", "TRAVERSE", "FERMINIA", "JAUREGUI", "VUCETICH", "FRAGNAUD",
        "SANDRINI", "ZORZALES", "CHAÑARES", "CIPRECES", "CASTAÑOS", "CEBALLOS", "GALLEGOS", "PATRICIO",
        "ALAMEDAS", "AZUCENAS", "BALLENAS", "CAMELIAS", "CHARITAS", "CORVINAS", "HIGUERAS", "PALMERAS",
        "TORTUGAS", "VIOLETAS", "ABEDULES", "ABIPONES", "ARENQUES", "ARRIEROS", "CANDILES", "CARDALES",
        "CIRUELOS", "CLAVELES", "DELFINES", "GERANIOS", "GRANADOS", "HALCONES", "HELECHOS", "JACINTOS",
        "JAZMINES", "MALVONES", "MANZANOS", "MAPUCHES", "MINUANES", "MOCORETA", "NARANJOS", "NARVALES",
        "NAUTILUS", "OLIVARES", "PARAISOS", "PEÑASCOS", "PLATANOS", "PLATEROS", "SALMONES", "DE ABRIL",
        "DE JULIO", "BENTEVEO", "CENCERRO", "COLMENAR", "FLAMENCO", "GAVIOTIN", "JILGUERO", "LEÑATERO",
        "PEJERREY", "PICAFLOR", "PIRINCHO", "TORDILLO", "QUEBRADA", "RATONERA", "SERRANIA", "TIJERETA",
        "TROPILLA", "CACHIRLA", "ACACIAS", "ADRIANA", "CAROYAS", "CASEROS", "CECILIA", "CERRITO",
        "248 BIS", "CORDOBA", "DANIELA", "709 BIS", "DOMINGO", "DOROTEA", "DORREGO", "ECUADOR",
        "CLAUDIA", "HUARPES", "IGNACIO", "LA TABA", "EUGENIA", "LUCANIA", "LUCIANO", "697 BIS",
        "HILARIO", "MANGORE", "PIERINA", "PILAGAS", "PIÑACAL", "POLONIA", "POSADAS", "PASTEUR",
        "RICARDO", "RODOLFO", "RONDEAU", "TOSCANA", "TUCUMAN", "URUGUAY", "USHUAIA", "ARMANDO",
        "ARMENIA", "PAMPERO", "PIONERO", "VIEYTES", "BEATRIZ", "BELGICA", "BERMEJO", "BOLIVAR",
        "BOLIVIA", "BRAULIO", "BRIGIDA", "CABILDO", "ALELIES", "EL CANO", "EL LAZO", "EL TERO",
        "ENRIQUE", "CHOCORI", "EVELINA", "FALUCHO", "FORMOSA", "FRANCIA", "GABRIEL", "GALICIA",
        "GUAYANA", "ISIDORO", "CENTRAL", "JACINTO", "JOAQUIN", "LAPRIDA", "LEANDRO", "LEGH II",
        "LETICIA", "LILIANA", "LINIERS", "LOBERIA", "HERMIDA", "MARCELA", "MARIANA", "MARIANO",
        "LAFQUEN", "PEHUAJO", "MATILDE", "MELINAO", "MENDOZA", "TINGUES", "LA LOMA", "NAPOLES",
        "NARCISO", "NATALIA", "NEUQUEN", "OLLEROS", "OSVALDO", "PASCUAL", "SICILIA", "ROBERTO",
        "ROTONDA", "YOLANDA", "MARQUEZ", "EDUARDO", "CAMUSSO", "PRIMERA", "GUEVARA", "MOLTENI",
        "NORESTE", "PAOLERA", "ESTEBAN", "ESTADOS", "MALABIA", "SANDINO", "ARTIGAS", "COYUNCO",
        "REFORMA", "SOLEDAD", "POLITIS", "DIETSCH", "GENERAL", "JOSE DE", "DEL MAR", "SEVILLA",
        "MARCONI", "DE MELO", "SOSIEGO", "NAVARRA", "DACHARY", "LUGONES", "GUSTAVO", "QUIROGA",
        "MARINOS", "SENADOR", "\"LOLA\"\"", "J PAYRO", "RIZZUTO", "LA MAZA", "CALCUTA", "FURLONG",
        "Y GOIRI", "CORSINI", "MIRAMAR", "GMEINER", "ACEVEDO", "KENNEDY", "ANTUNEZ", "GAZZOLO",
        "PEDRONI", "BONANNI", "PACHECO", "LARRAYA", "GORRITI", "ALBERDI", "DE ASIS", "AUSTRAL",
        "LUISONI", "DEL SUR", "BALLINA", "CABRERA", "MOGOTES", "LOMITAS", "ESTRADA", "COLMENA",
        "DAVALOS", "ARMONIA", "ANTONIO", "GUARANI", "NICOLAS", "ROSARIO", "JUAN B.", "VIGNOLO",
        "CACIQUE", "LORENZO", "ANDRADE", "VICENTE", "MAFALDA", "BRAGADO", "ORTIGAS", "DE CUBA",
        "FLEMING", "DOLORES", "SANCHEZ", "ONEGLIA", "ALVAREZ", "PIZARRO", "SARTORA", "ALBERTO",
        "UNAMUNO", "BASILIO", "BESTOSO", "BIZNAGA", "KONTIKI", "LACAMTU", "FAGNANI", "BALERDI",
        "CERETTI", "LARRETA", "SERRANO", "ALCORTA", "MISTRAL", "ROSALES", "BRUMANA", "PEREYRA",
        "ALLENDE", "VERGARA", "MAGALDI", "BRADLEY", "GAUDINI", "AZUCENA", "PEDRAZA", "MAIZANI",
        "MARCELO", "MACHADO", "CERDEÑA", "N. ALEM", "CAMARGO", "FRESEDO", "HORNERO", "TEJEDOR",
        "DE PUAN", "DE ROMA", "SERAPIO", "COPAHUE", "SALGARI", "MAHATMA", "SARANDI", "MARUCHA",
        "AGUIRRE", "STROBEL", "URRUTIA", "EL FARO", "HERMOSO", "COMALAL", "EL TURF", "BOUCHEZ",
        "DEJORGE", "GUSTAVA", "OCTUBRE", "AUGUSTO", "JUAN DE", "CAFRUNE", "AZURDUY", "CANESSA",
        "DE CARO", "CABEZAS", "FERRARI", "GUILLEN", "MEDRANO", "FALKNER", "RAZZANO", "DEL ORO",
        "ARROYOS", "PAJAROS", "A. PEÑA", "B. GOÑI", "LABORDE", "MARIANI", "VARESSE", "SAGASTA",
        "- BATAN", "TILOS B", "CEREZOS", "MATANZA", "AGUAPEY", "COSQUIN", "ALMEJAS", "AZALEAS",
        "ENCINAS", "FRECIAS", "MORERAS", "NUTRIAS", "RETAMAS", "TONINAS", "TOTORAS", "AZTECAS",
        "CORALES", "FOGONES", "FRESNOS", "MATACOS", "MIMBRES", "NOGALES", "PERALES", "QUILMES",
        "TERCERO", "HEDEN G", "DE MAYO", "ESTRIBO", "GORRION", "MILAGRO", "MIRADOR", "REMANSO",
        "ROSILLO", "TAJAMAR", "TOBIANO", "SERRANA", "TORCAZA", "VAGUADA", "VIHUELA", "ALONDRA",
        "CIGUEÑA", "GAVIOTA", "12 BIS", "13 BIS", "ALICIA", "ANALIA", "ANGELA", "CANADA",
        "CANNES", "CARLOS", "CATANI", "CEDROS", "DAMIAN", "DANIEL", "DERQUI", "67 BIS",
        "CAMILO", "TERESA", "HAYDIN", "HECTOR", "HUILEN", "ESTELA", "HIGINO", "JUNCAL",
        "JULIAN", "MARCOS", "PINCEN", "SILVIA", "RAWSON", "ARAGON", "AROMOS", "ARTURO",
        "MARLIN", "VERTIZ", "VICTOR", "AYELEP", "VIEDMA", "AYOLAS", "ALTAIR", "BRASIL",
        "TANDIL", "ADOLFO", "ALSINA", "ALVARO", "VULCAN", "EGIDIO", "EMILIO", "CHUBUT",
        "ESPAÑA", "FABIAN", "FELIPE", "FRANCA", "FRIULI", "GABOTO", "GENARO", "GENOVA",
        "GRECIA", "ISABEL", "ITALIA", "ESQUEL", "LARREA", "LLIFEN", "MARTIN", "MEJICO",
        "MIGUEL", "PELAYO", "PERDIZ", "MORENO", "NESTOR", "OFELIA", "OVIDIO", "PARANA",
        "RAQUEL", "SUSANA", "ROSANA", "YAPEYU", "ZURITA", "DE HOZ", "HUDSON", "ANDREA",
        "RACEDO", "PLANES", "BARROS", "FANGIO", "KRAUSE", "JEWETT", "PADRES", "MILLAN",
        "HIERRO", "LLAMAS", "MONTES", "MANUEL", "ZABALA", "ALVEAR", "INVADO", "RETAZO",
        "OTIMIO", "HORNOS", "BQ.P.R", "DE ORO", "GOMARA", "ORTEGA", "THETIS", "GERMAN",
        "SEGURA", "IGUAZU", "BAYLEY", "GUEMES", "CANATA", "CALAZA", "RATERY", "GRANDE",
        "SERENA", "OCAMPO", "ARROYO", "GASCON", "CASTEX", "FLORES", "GASSET", "VERDES",
        "LIBANO", "ROLDAN", "BULNES", "PINZON", "FRANCO", "JAVIER", "CANOSA", "CURROS",
        "THAMES", "ESTERO", "IRIZAR", "AMIGOS", "GABITO", "BORDON", "CORONA", "NASSER",
        "BOTANA", "GUERRA", "ALEGRE", "HELMER", "ARENAL", "LOHIOL", "CARASA", "CASTRO",
        "MICHEL", "ACOSTA", "EDISON", "FERMIN", "E. BIS", "GALDOS", "STORNI", "AGUADO",
        "CANARO", "FERRER", "ISRAEL", "PEREDA", "MOISES", "CAROLA", "ANGELI", "MORRIS",
        "DAVILA", "JUAN M", "Y LEON", "CANDIL", "CARRIL", "JOSE S", "HALCON", "NARWAL",
        "NOMADE", "PUMARA", "CAYADO", "DANERI", "SASTRE", "TOBAGO", "CABRAL", "PAGANO",
        "BONNET", "CAYROL", "CHAVEZ", "GOROZO", "MARIAS", "MENDEZ", "DE MAR", "OLAZAR",
        "ZARATE", "VILLAR", "JOSE M", "AROLAS", "MALLEA", "GARCIA", "BALBIN", "CHULAK",
        "TREBOL", "LEPERA", "VILERT", "ZAMORA", "TIZONE", "BORBON", "ISCHIA", "ZORZAL",
        "SUAREZ", "UNIDOS", "GARDEL", "PIGOZI", "TEJADO", "CORTES", "URANGA", "BLANCO",
        "MOLISE", "JUAREZ", "COUREL", "FIERRO", "OVIEDO", "GAUCHA", "PERITO", "MADRYN",
        "FATIMA", "NEVADO", "VARELA", "BLANCA", "ALIPPI", "AVALOS", "OLIVIA", "NERUDA",
        "GOYENA", "MARMOL", "PANTEA", "YAHATY", "LELOIR", "PARERA", "LAURIE", "ALONSO",
        "VERNET", "ALJIBE", "LUCERO", "ORIONE", "CEIBOS", "CURACO", "JACHAL", "FOCA B",
        "DALIAS", "FRESAS", "OSTRAS", "ABETOS", "ALAMOS", "APEROS", "JUNCOS", "LIRIOS",
        "MIRLOS", "NARDOS", "OMBUES", "ROBLES", "SAUCES", "NOGOYA", "SUQUIA", "BENITO",
        "AGUADA", "LAGUNA", "ALAZAN", "HORCON", "JAGUEL", "RECADO", "RINCON", "LOMADA",
        "MATERA", "SURE?A", "AURORA", "COLINA", "CUESTA", "ANGEL", "DARDO", "NORTE",
        "DIEGO", "695 B", "HUDER", "JUANA", "LUCIO", "LUISA", "HILDA", "JUSTO",
        "PIGUE", "SIOUX", "SOFIA", "PAULA", "TULIO", "TUPAC", "UDINE", "COLON",
        "BASSI", "BRUNO", "0 BIS", "2 BIS", "4 BIS", "6 BIS", "8 BIS", "ELENA",
        "CHACO", "ELINA", "ELISA", "CHILE", "FARRO", "FELIX", "IRALA", "IRENE",
        "JORGE", "JUJUY", "JULIA", "LAURA", "LIDIA", "ESTER", "LULES", "MABEL",
        "MAIPU", "MARIA", "MARIO", "MARTA", "MAURO", "MIRTA", "NOEMI", "TOBAS",
        "OSCAR", "PABLO", "PEDRO", "SALTA", "SOLIS", "TAGLE", "ILLIA", "PILAR",
        "ALDAO", "RAMOS", "RAMON", "JUKIC", "ROMAN", "BRAVA", "PADRE", "ERREA",
        "TANGO", "MAYOR", "FITTE", "SALLE", "CLARA", "PIRAN", "PERON", "ABATE",
        "VIDAL", "SAVIO", "PAYRO", "JUNCO", "SOLER", "RIEGO", "GOIRI", "CAMET",
        "PLATA", "BOSCH", "RAUCH", "LOPEZ", "YAHAN", "LAMAS", "BOMBA", "MANZI",
        "SIRIA", "LUJAN", "LORCA", "CESAR", "CZETZ", "ROQUE", "MADRE", "VALLE",
        "OLIVA", "CAMPO", "TORRE", "HEDEN", "HONDO", "ROXLO", "VADIS", "CUTAY",
        "ROFFO", "OCAÑA", "ARAOZ", "SOLAR", "LUCAS", "TALAS", "TRUCO", "PAMPA",
        "BALET", "FIRPO", "ROJAS", "LLOSA", "FUEGO", "VOLTA", "GARAU", "PATOS",
        "TOHEL", "CROCE", "ENEAS", "CLETO", "BIS B", "ARANA", "DANTE", "PINTO",
        "AMADO", "AYALA", "REJON", "ISAAC", "TADEO", "ARRUE", "PALMA", "LAJAS",
        "PARRA", "ALICE", "SAENZ", "WILDE", "BLANC", "ITATI", "ROSAS", "DAZEO",
        "JUNTA", "WALSH", "CUELI", "BERRA", "MELGA", "CASAL", "INCAS", "LINCH",
        "AIRES", "HUAPI", "LATUF", "MARIS", "ADELA", "ROCHA", "PAINE", "LANIN",
        "COPAC", "VERNE", "TOMAS", "MANSO", "MUÑOZ", "CURIE", "BRAVO", "ARVES",
        "FERRE", "DARIO", "VERDE", "SMITH", "MARTI", "AGOTE", "ULTRA", "VIGIA",
        "CHICO", "TEJAR", "BOSCO", "TILOS", "ATUEL", "BELEN", "DULCE", "CALAS",
        "FOCAS", "HAYAS", "HERAS", "LISAS", "LOMAS", "ORCAS", "ARCES", "LIMAY",
        "OLMOS", "ORTIZ", "TAPES", "NEGRO", "TEUCO", "ZAINO", "CERRO", "CHAJA",
        "MATEO", "MIXTO", "MONTE", "RODEO", "SULKY", "TORDO", "POSTA", "RIOJA",
        "LEGUA", "SARA", "OMBU", "INES", "JUAN", "LUIS", "PERU", "ROSA",
        "ABEL", "FOCA", "ACHA", "ALDO", "ELSA", "JOSE", "NN A", "NN B",
        "NORA", "OLGA", "PUAN", "RITA", "RUIZ", "AGUA", "GOLF", "MELO",
        "DIAZ", "BLAS", "COBO", "JARA", "MAZA", "PASO", "INDA", "BAYA",
        "LUNA", "R.P.", "ASIS", "FRAY", "DAYS", "LURO", "BIS)", "CUBA",
        "PEÑA", "SECO", "ENZO", "CRUZ", "LEON", "PINO", "GAUL", "ALEM",
        "ROMA", "RAUL", "KORN", "FARO", "TURF", "SOSA", "NUÑO", "CARO",
        "VIVA", "OLAN", "TERU", "GOÑI", "ARLT", "PURA", "RIOS", "ALIO",
        "CANE", "FLOR", "QUEN", "AZUL", "HUEN", "TALA", "TABA", "CANO",
        "LAZO", "TERO", "LOMA", "EMA", "EVA"
    ];

    let filtros = {
        rojo: ["marzo", "diciembre", "estudiantes", "estudiante", "estudiantil", "temporal", "9 meses", "12 meses", "sin gas", "reservado", "temporada", "temporario"],
        verde: ["24 meses", "lavadero", "garantia propietaria", "ICL"],
        amarillo: ["recibo de sueldo", "demostracion de ingresos", "USD"]
    };

    const LIMITE = 780000;
    const regexMontos = /(?:(?:U\$S|\$)\s?)?(?:\d{1,3}(?:[.,]\d{3})+|\d{6,})(?!\d)/gi;

    // Helper to escape special regex characters
    const escapeRegex = (str) => str.replace(/[.*+?^$${}()|[\]\\]/g, '\\$&');

    // Improved Regex to handle "al", commas, and spaces
    const regexDireccion = new RegExp(`\\b(${STREETS.map(escapeRegex).join("|")})\\s*(?:,\\s*|al\\s+|al\\s*,\\s*)*(\\d+)\\b`, "gi");

    // Persistence for 'seen' apartments
    let seenApartments = GM_getValue('seen_apartments', []);

    GM_addStyle(`
        .visto-btn { margin-left: 5px; padding: 2px 5px; font-size: 10px; cursor: pointer; background: #666; color: white; border: 1px solid #999; border-radius: 3px; }
        .visto-btn:hover { background: #444; }
        .visto-btn.active { background: #28a745; border-color: #1e7e34; }
        .address-seen { text-decoration: line-through; opacity: 0.6; }
    `);

    function normalizarMonto(str) {
        return parseInt(str.replace(/U\$S|\$/gi, "").replace(/[.,\s]/g, ""), 10);
    }

    function toggleVisto(id, btn, span) {
        if (seenApartments.includes(id)) {
            seenApartments = seenApartments.filter(a => a !== id);
            btn.classList.remove('active');
            span.classList.remove('address-seen');
            btn.textContent = "visto";
        } else {
            seenApartments.push(id);
            btn.classList.add('active');
            span.classList.add('address-seen');
            btn.textContent = "✓";
        }
        GM_setValue('seen_apartments', seenApartments);
    }

    function marcar(node) {
        if (node.nodeType === 1 && ["SCRIPT", "STYLE", "TEXTAREA", "INPUT", "NOSCRIPT"].includes(node.tagName)) return;

        if (node.nodeType === 3) {
            let text = node.nodeValue;
            if (!text || text.trim().length === 0) return;
            if (node.parentNode && node.parentNode.hasAttribute && node.parentNode.hasAttribute('data-filtro')) return;

            let hasMatches = false;
            let parts = [{ type: 'text', value: text }];

            const applyFilter = (regex, type, style, isAddress = false) => {
                let newParts = [];
                parts.forEach(part => {
                    if (part.type !== 'text') {
                        newParts.push(part);
                        return;
                    }
                    let lastIndex = 0;
                    let match;
                    regex.lastIndex = 0;
                    while ((match = regex.exec(part.value)) !== null) {
                        if (match.index > lastIndex) {
                            newParts.push({ type: 'text', value: part.value.substring(lastIndex, match.index) });
                        }

                        let shouldHighlight = true;
                        if (type === 'precio') {
                            const v = normalizarMonto(match[0]);
                            if (isNaN(v) || v < LIMITE) shouldHighlight = false;
                        }

                        if (shouldHighlight) {
                            newParts.push({ type: 'span', value: match[0], marker: type, style: style, isAddress: isAddress });
                            hasMatches = true;
                        } else {
                            newParts.push({ type: 'text', value: match[0] });
                        }
                        lastIndex = regex.lastIndex;
                    }
                    if (lastIndex < part.value.length) {
                        newParts.push({ type: 'text', value: part.value.substring(lastIndex) });
                    }
                });
                parts = newParts;
            };

            // Apply Filters
            Object.keys(filtros).forEach(color => {
                let style = color === "rojo" ? "background:red;color:white;font-weight:bold;" :
                    color === "verde" ? "background:limegreen;color:black;font-weight:bold;" :
                        "background:gold;color:black;font-weight:bold;";
                filtros[color].forEach(word => applyFilter(new RegExp(`(${word})`, "gi"), color, style));
            });
            applyFilter(regexMontos, 'precio', "background:red;color:white;font-weight:bold;");
            applyFilter(regexDireccion, 'direccion', "background:cyan;color:black;", true);

            if (hasMatches) {
                const fragment = document.createDocumentFragment();
                parts.forEach(part => {
                    if (part.type === 'text') {
                        fragment.appendChild(document.createTextNode(part.value));
                    } else {
                        const span = document.createElement('span');
                        span.setAttribute('data-filtro', part.marker);
                        span.style.cssText = part.style;
                        span.textContent = part.value;

                        if (part.isAddress) {
                            // Normalize ID for seenApartments: remove "al", commas, multiple spaces
                            const addrId = part.value.toUpperCase().replace(/[^A-Z0-9]/g, ' ').replace(/\s+/g, ' ').trim();
                            const btn = document.createElement('button');
                            btn.className = 'visto-btn';
                            btn.textContent = seenApartments.includes(addrId) ? "Visto ✓✓" : "visto";
                            if (seenApartments.includes(addrId)) {
                                btn.classList.add('active');
                                span.classList.add('address-seen');
                            }
                            btn.onclick = (e) => {
                                e.preventDefault();
                                e.stopPropagation();
                                toggleVisto(addrId, btn, span);
                            };
                            fragment.appendChild(span);
                            fragment.appendChild(btn);
                        } else {
                            fragment.appendChild(span);
                        }
                    }
                });
                try {
                    if (node.parentNode) node.parentNode.replaceChild(fragment, node);
                } catch (e) {
                    console.warn("[Rent Filter] Failed to replace node:", e);
                }
            }
        } else {
            Array.from(node.childNodes).forEach(marcar);
        }
    }

    /* ===== OBSERVER ===== */
    let observer;
    function startObserving() {
        if (observer) observer.disconnect();
        observer = new MutationObserver((mutations) => {
            mutations.forEach((mutation) => {
                mutation.addedNodes.forEach((node) => marcar(node));
            });
        });
        observer.observe(document.body, { childList: true, subtree: true });
    }

    function aplicarTodo() {
        marcar(document.body);
        startObserving();
    }

    /* ===== UI ELEMENTS ===== */
    function setupUI() {
        const btn = document.createElement("button");
        btn.textContent = "⚙";
        btn.id = "rf-settings-btn";
        btn.style.cssText = "position:fixed; bottom:10px; right:10px; z-index:999999; padding:8px; border-radius:8px; cursor:pointer; background:#222; color:#fff; border:1px solid #555;";
        document.body.appendChild(btn);

        const updateBtn = document.createElement("button");
        updateBtn.textContent = "🔄";
        updateBtn.style.cssText = "position:fixed; bottom:55px; right:10px; z-index:999999; padding:8px; border-radius:50%; cursor:pointer; background:black; color:white; border:1px solid white; font-size:14px;";
        updateBtn.onclick = () => window.open("https://raw.githubusercontent.com/Wapply/word-filter/main/rent-filter.user.js", "_blank");
        document.body.appendChild(updateBtn);

        const panel = document.createElement("div");
        panel.id = "rf-panel";
        panel.style.cssText = "position:fixed; bottom:100px; right:10px; background:#111; color:#fff; padding:10px; border-radius:10px; font-size:12px; display:none; z-index:999999; max-width:260px; border: 1px solid #444;";

        function renderPanel() {
            panel.innerHTML = "";
            Object.keys(filtros).forEach(color => {
                const titulo = document.createElement("b");
                titulo.textContent = color.toUpperCase();
                panel.appendChild(titulo);
                panel.appendChild(document.createElement("br"));
                filtros[color].forEach((f, i) => {
                    const row = document.createElement("div");
                    row.style.margin = "2px 0";
                    row.innerHTML = `< span style = "display:inline-block; width:180px; overflow:hidden; text-overflow:ellipsis; white-space:nowrap;" > ${f}</span >
    <button style="background:red; color:white; border:none; border-radius:3px; cursor:pointer;" data-c="${color}" data-i="${i}">✖</button>`;
                    panel.appendChild(row);
                });
                const input = document.createElement("input");
                input.placeholder = "Agregar...";
                input.style.cssText = "width:100%; margin-top:4px; background:#fff; color:#000; border-radius:4px; padding:3px;";
                input.onkeydown = e => {
                    if (e.key === "Enter" && input.value.trim()) {
                        filtros[color].push(input.value.trim());
                        input.value = "";
                        renderPanel(); aplicarTodo();
                    }
                };
                panel.appendChild(input);
                panel.appendChild(document.createElement("br"));
            });
            panel.querySelectorAll("button[data-c]").forEach(b => {
                b.onclick = () => {
                    filtros[b.dataset.c].splice(b.dataset.i, 1);
                    renderPanel(); aplicarTodo();
                };
            });
        }
        btn.onclick = () => {
            panel.style.display = panel.style.display === "none" ? "block" : "none";
            renderPanel();
        };
        document.body.appendChild(panel);
    }

    if (document.readyState === "complete" || document.readyState === "interactive") {
        setupUI(); aplicarTodo();
    } else {
        window.addEventListener("DOMContentLoaded", () => { setupUI(); aplicarTodo(); });
    }
})();



