// ==UserScript==
// @name         Rent Filter
// @description  A Word Filter Script with MutationObserver and GTM Safety
// @author       Wapply
// @namespace    http://tampermonkey.net/
// @updateURL    https://raw.githubusercontent.com/Wapply/word-filter/main/rent-filter.user.js
// @downloadURL  https://raw.githubusercontent.com/Wapply/word-filter/main/rent-filter.user.js
// @version      4.7
// @match        *://*/*
// @grant        GM_setValue
// @grant        GM_getValue
// @grant        GM_addStyle
// ==/UserScript==

(function () {
    'use strict';

    // List of streets (sorted by length descending for better matching)
    // Includes variations for informal matching (stripped prefixes and suffixes)
    const STREETS = [
        "PASEO COSTANERO DEL SUD PRESIDENTE ARTURO HUMBERTO ILLIA", "COSTANERO DEL SUD PRESIDENTE ARTURO HUMBERTO ILLIA", "\"ATAHUALPA YUPANQUI \"\"HECTOR R. CHAVERO\"\"\"", "CNO. CONSTITUCION - CNO.A LA TAPERA NORTE", "CNO. RUTA 88 A CALLE LIB.GRAL.SAN MARTIN", "MARCELO GUSTAVO FRAGATA MARQUEZ TENIENTE", "DIAGONAL ESTADOS UNIDOS DE NORTEAMERICA", "MARIA TERESA FERRARI DE GAUDINO DOCTORA",
        "MANUEL I. GONZALEZ GUERRICO INTENDENTE", "GIACHINO PEDRO EDUARDO CAPITAN FRAGATA", "JOSE LUIS GERONIMO CAMUSSO INTENDENTE", "HECTOR ANTONIO DUFRECHOU MAR PRIMERA", "\"ERNESTO \"\"CHE\"\" GUEVARA COMANDANTE\"", "JUANA DE IBARBOUROU JUANA FERNANDEZ", "PASAJE VECINALISTA ABELARDO MOLTENI", "ACCESO PRINCIPAL A CIRC 3 PARCS 37",
        "CNO. COL BARRAGAN A LIMITE NORESTE", "REDUCCION NUESTRA SEÑORA DEL PILAR", "ENRIQUE RAU OBISPO MONSEÑOR DOCTOR", "NUESTRA SEÑORA DE LOS DESAMPARADOS", "CARLOS M. DELLA PAOLERA INGENIERO", "CNO. CIRC 2 ENTRE PAR 388AA Y 390", "CNO. CIRC 2 ENTRE PAR 894D Y 873B", "CNO. CIRC 2 ENTRE PAR 898A Y 891D",
        "CNO. CIRC 3M ENTRE FRAC 1-2 Y 5-6", "CNO. CIRC 3M ENTRE FRAC 1-5 Y 2-6", "CNO. CIRC 3 ENTRE PARC 49M Y 50 A", "JOSE LEONIDAS ARDILES TENIENTE 1º", "AVENIDA MIGUEL A. MARTINEZ DE HOZ", "FELIX  OSCAR ARTUSO SUBOFICIAL 1º", "DIAGONAL DALMACIO VELEZ SARSFIELD", "DIAGONAL ENRIQUE SANTOS DISCÉPOLO",
        "DIAGONAL GUILLERMO ENRIQUE HUDSON", "MARIO ANTONIO CISNERO SARGENTO 1º", "PASEO CELSO NICANOR  ALDAO DOCTOR", "ACCESO A CIRC 2 PARC 344B Y 345B", "CAMINO IV ENTRE PARC 72 C Y 73 B", "CARLOS DE CHAPEAUROUGE INGENIERO", "CNO. EST. CHAPADMALAL - OTAMENDI", "CNO. EST. COBO - EA. ITUZAINGO B",
        "CNO. RUTA 226 A CIRC 2 PARC 796A", "AVENIDA SAN MARCELINO CHAMPAGNAT", "MARADONA LAUREANO ESTEBAN DOCTOR", "MIGUEL DE ANDREA MONSEÑOR DOCTOR", "CNO. CIRC 2 ENTRE PAR 923 Y 914", "CNO. CIRC 2 ENTRE PAR 949 Y 938", "CNO. RUTA 226 A CIRC 2 PARC 800", "CNO. RUTA 226 A CIRC 2 PARC 805",
        "CNO. RUTA 226 A CIRC 2 PARC 886", "DIEGO MARTIN BELLINZONA SOLDADO", "ACCESO A CIRC 2 PARC 948B Y 951", "ANTONIO LUIS GALLO SUBOFICAL 1º", "EDUARDO RACEDO TENIENTE GENERAL", "ESTANCIA SAN JULIAN DE VIVORATA", "NUESTRA SEÑORA DE LA CONCEPCION", "PASCUAL RENE BLANCO SARGENTO 1º",
        "CNO.A LOS PATOS - EL COYUNCO B", "CNO.CNIA BARRAGAN-PJE HERMANAS", "CNO.EA. LAS LOMITAS - OTAMENDI", "CNO. EST. COBO - EA. ITUZAINGO", "CNO. PARQUE HERMOSO A AEROCLUB", "CNO.STA PAULA-PJE LAS HERMANAS", "IDIOMA INTERNACIONAL ESPERANTO", "RICARDO MARIO GURRIERE SOLDADO",
        "TRANSPORTE ISLA DE LOS ESTADOS", "VICENTE MONTES CARBALLO DOCTOR", "AVENIDA PATRICIO PERALTA RAMOS", "FEDERICO C. BELTRAMI INGENIERO", "GUSTAVO MARCELO PLANES SOLDADO", "ESTADOS UNIDOS DE NORTEAMERICA", "JOSE DANTE FAUR SUB OFICIAL.2º", "MARQUEZ RAMON TENIENTE CORONEL",
        "MIGUEL ANGEL CASTELLANO DOCTOR", "PEDRO IGNACIO DE CASTRO BARROS", "RUTA JARDIN JUAN MANUEL FANGIO", "CARLOS EDUARDO KRAUSE CAPITAN", "CNO. CIRC 3J ENTRE FRAC 3 Y 4", "CNO. CIRC 3J ENTRE FRAC 5 Y 6", "CNO.ENTRADA EST. EL SOLITARIO", "CNO.EST COBO-COLONIA BARRAGAN",
        "CNO.S.DE LOS PADRES-V.SERRANA", "DANIEL ANTONIO JUKIC TENIENTE", "DE MARIA DAVID JEWETT CORONEL", "TEODORO SANCHEZ DE BUSTAMANTE", "JOSE SEVERO FELICIANO MALABIA", "RIO DE LA PLATA-BO. AUTODROMO", "ROMPE HIELOS GRAL. SAN MARTIN", "AUGUSTO CESAR SANDINO GENERAL",
        "AVENIDA 10 DE FEBRERO DE 1874", "AVENIDA ESTANCIA OJO DEL AGUA", "ESC. SUR - CNO. A EL SALVADOR", "JOSE ANTONIO ALVAREZ CONDARCO", "JOSE GERVASIO ARTIGAS GENERAL", "ESTANCIA LAGUNA DE LOS PADRES", "LIBERTADOR SAN MARTIN GENERAL", "MARIA ADELINA FUNES DE MILLAN",
        "MARTINEZ DE HOZ FLORENCIO BIS", "PASAJE JUAN CARLOS CASTAGNINO", "RAMIREZ  FRANCISCO J. GENERAL", "CNO. RIO PINTO - BORDEU JUAN", "CNO.RUTA 226-A DE LOS PADRES", "CRUCERO ARA BELGRANO GENERAL", "DIAGONAL JUSTO ERNESTO ROMAN", "CNO.A.LAS BRUSQUITAS-L BRAVA",
        "CNO.A LOS PATOS - EL COYUNCO", "DIAGONAL ESTANCIA LA REFORMA", "JOSE LUIS DEL HIERRO SOLDADO", "SAN PIO DE PIETRELCINA PADRE", "AVENIDA CENTRAL ISLA SOLEDAD", "AVENIDA JUAN B. JUSTO DOCTOR", "BOSCH MAYOL GUILLERMO DOCTOR", "GASPAR MELCHOR DE JOVELLANOS",
        "JORGE ALBERTO LLAMAS SOLDADO", "JORGE NICOLAS POLITIS PILOTO", "JORGE RODOLFO DIETSCH DOCTOR", "JUAN TORRES DE VERA Y ARAGON", "ROCA JULIO ARGENTINO GENERAL", "URQUIZA JUAN JOSE DE GENERAL", "12 - GLORIA DE LA PELEGRINA", "14 - GLORIA DE LA PELEGRINA",
        "CNO.MARAYUI - EA STA ISABEL", "DIAGONAL SANTA ROSA DEL MAR", "CAMINO DEL CABILDO INDIGENA", "LUIS GUILLERMO SEVILLA CABO", "10 - GLORIA DE LA PELEGRINA", "AVENIDA ANTARTIDA ARGENTINA", "AVENIDA CENTENO NORBERTO O.", "AVENIDA FERMIN ERREA DOCTOR",
        "AVENIDA FRANCISCO QUINTEROS", "16 - GLORIA DE LA PELEGRINA", "VICTORIANO E. MONTES DOCTOR", "BRIGADIER ROSAS JUAN MANUEL", "771 BIS - PLAYA CHAPADMALAL", "\"ANIBAL TROILO \"\"PICHUCO\"\"\"", "EL ESTRIBO - LOMAS DEL GOLF", "CIRCUITO SAN MARTIN GENERAL",
        "FRANCISCO SAVERIO SCARPATTI", "GUILLERMO MARCONI INGENIERO", "JOSE ANDRES PACHECO DE MELO", "JUAN MARTIN ZABALA MONSEÑOR", "LUIS PIEDRABUENA COMANDANTE", "MARCELO T. DE ALVEAR DOCTOR", "OMAR ALDO FERREYRA  SOLDADO", "CELSO NICANOR  ALDAO DOCTOR",
        "RAMON DE LA COLINA COMODORO", "4 - GLORIA DE LA PELEGRINA", "6 - GLORIA DE LA PELEGRINA", "7 - GLORIA DE LA PELEGRINA", "9 - GLORIA DE LA PELEGRINA", "CNO. LIMITE NOROESTE NORTE", "CNO.STA PAULA - EL SOSIEGO", "COMUNIDAD FORAL DE NAVARRA",
        "DE DIOS FILIBERTO JUAN BIS", "DIAGONAL SANTANGELO INVADO", "CNO. A. LA TAPERA AL NORTE", "PREFECTURA NAVAL ARGENTINA", "ROLANDO PACHOLEZUK SOLDADO", "AVENIDA VICTORIO TETAMANTI", "BALDOMERO FERNANDEZ MORENO", "B/P VIRGEN DE LAS LAGRIMAS",
        "5 - GLORIA DE LA PELEGRINA", "8 - GLORIA DE LA PELEGRINA", "ACCESO A CIRC 2 PARC 889 B", "ACCESO A CIRC 2 PARC 911 A", "ACCESO A CIRC 3 PARC 225 J", "ALEJANDRO DACHARY TENIENTE", "ANTONIO MARIA DIAZ SOLDADO", "ENRIQUE ANGELELLI MONSEÑOR",
        "ENRIQUE FINOCHIETTO DOCTOR", "FAUSTO GAVAZZI TENIENTE 1º", "GUARDACOSTA ISLAS MALVINAS", "DIAGONAL CORTADA DEL TANGO", "JUAN JOSE  FALCONIER MAYOR", "LAS TRES MARIAS-L.DEL GOLF", "MARCELO JULIO FITTE DOCTOR", "MOSCONI ENRIQUE C. GENERAL",
        "NUESTRA SRA DE SCHOENSTATT", "ACCESO A CIRC 2 PARC 361H", "IV ENTRE PARC 72 C Y 73 B", "CNO. CIRC 3M ENTRE FRAC 1", "CNO.EST CAMET - EL RETAZO", "DIAGONAL LEOPOLDO LUGONES", "DIAGONAL OVIDIO ZUBIAURRE", "TESONE JUAN OTIMIO DOCTOR",
        "PORTAVIONES INDEPENDENCIA", "REFORMA UNIVERSITARIA BIS", "PAUNERO WENCESLAO GENERAL", "TRANSPORTE BAHIA SAN BLAS", "TRANSPORTE CABO DE HORNOS", "ARTURO  MARTIN  JAURETCHE", "MIGUEL A. MARTINEZ DE HOZ", "BERNARDO NUSDORFFER PADRE",
        "ACCESO A CIRC 2 PARC 954B", "CALLE 663 (LOS CALAMARES)", "FLORENCIO MARTINEZ DE HOZ", "DIAGONAL ELPIDIO GONZALEZ", "JUAN BAUTISTA DE LA SALLE", "MARIANO ACOSTA GOBERNADOR", "MARIO ABEL AMAYA DIPUTADO", "PSJE.EL CARDENAL - BQ.P.R",
        "PSJE.EL ZORZAL-BQ.P.RAMOS", "TOMAS MANUEL DE ANCHORENA", "ZUVIRIA MARTINEZ  GUSTAVO", "ACCESO A CIRC 2 PARC 409", "ACCESO A ESCOLLERA NORTE", "CNO.DEL CABILDO INDIGENA", "CNO.DEL CACIQUE CANGAPOL", "CNO.EL CASAL - STA CLARA",
        "CNO.EL TEJADO - EST COBO", "DEL VALLE MARIA REMEDIOS", "DIAGONAL HORACIO QUIROGA", "JOSE MARIA PIRAN GENERAL", "JUSTO SANTA MARIA DE ORO", "JUSTO S. LOPEZ DE GOMARA", "PDO. DE GRAL. PUEYRREDON", "TRIPULANTES DEL FOURNIER",
        "AV. DE LOS LOBOS MARINOS", "AVENIDA  DE LA HERRADURA", "AVENIDA JUAN HECTOR JARA", "AVENIDA PRESIDENTE PERON", "SAN MARCELINO CHAMPAGNAT", "BALDOMERO JOSE DE VIEDMA", "B/P E. SAN ANTONIO ABATE", "ACCESO A CIRC 2 PARC 924",
        "ALBERT SCHWEITZER DOCTOR", "CALLE 3 (GODOY CRUZ BIS)", "ENZO BORDABEHERE SENADOR", "CIUDAD DE LAS FLORES BIS", "GRIERSON CECILIA DOCTORA", "DALMACIO VELEZ SARSFIELD", "ENRIQUE SANTOS DISCÉPOLO", "GUILLERMO ENRIQUE HUDSON",
        "JOSE COEHLO DE MEYRELLES", "ESTANCIA CABO CORRIENTES", "CALLE 9 -  COSTA ALEGRE", "CELESTINO VIDAL CORONEL", "CNO.RUTA 226 - LA LAURA", "DAVID ORTEGA PRESBITERO", "\"DOLORES MORA \"\"LOLA\"\"\"", "HECTOR TARANTINO DOCTOR",
        "MANUEL N. SAVIO GENERAL", "PESQ.AMAPOLA Y ANGELITO", "REGINA PACINI DE ALVEAR", "PASEO JESUS DE GALINDEZ", "TRANSPORTE BAHIA THETIS", "AVENIDA ROBERTO J PAYRO", "BENITO QUINQUELA MARTIN", "BOULEVARD ABDALA GERMAN",
        "843 - PLAYA CHAPADMALAL", "ACCESO A CIRC 3 PARC 8C", "CALLE 1 -  COSTA ALEGRE", "CALLE 2 -  COSTA ALEGRE", "CALLE 3 -  COSTA ALEGRE", "CALLE 5 -  COSTA ALEGRE", "CALLE 6 -  COSTA ALEGRE", "CALLE 7 -  COSTA ALEGRE",
        "CALLE 8 -  COSTA ALEGRE", "ERNESTO SEGURA MONSEÑOR", "FRANCISCO ANGEL RIZZUTO", "GUARDACOSTAS RIO IGUAZU", "GUILLERMO BAYLEY DOCTOR", "JOSE AGUSTIN DE LA MAZA", "MADRE TERESA DE CALCUTA", "MARTIN MIGUEL DE GUEMES",
        "MARTIN SANCHEZ DE JUNCO", "MIGUEL ESTANISLAO SOLER", "PADRE GUILLERMO FURLONG", "RAFAEL DE RIEGO GENERAL", "SABINO DE ARANA Y GOIRI", "VALLE VERDE - BO. CAMET", "ALGEL VICENTE PEÑALOZA", "ANDRES IGNACIO CORSINI",
        "CAMINO VIEJO A MIRAMAR", "SIERRA DE LOS DIFUNTOS", "DIAGONAL MANUEL CANATA", "DIAGONAL MAR DEL PLATA", "DIAGONAL RENE FAVALORO", "DIAGONAL SANTA CECILIA", "DIAGONAL ATLANTICO SUR", "JOSE M. CALAZA CORONEL",
        "JOSE RODRIGUEZ SOLDADO", "HERMANN GMEINER DOCTOR", "MANUEL ANTONIO ACEVEDO", "JULIO RATERY INGENIERO", "REPUBLICA DE SUDAFRICA", "0 CAMINO A SANTA CLARA", "VICENTE LOPEZ Y PLANES", "AVENIDA FELIX U. CAMET",
        "AVENIDA JUAN JOSE PASO", "PATRICIO PERALTA RAMOS", "BOULEVARD NUEVO BOSQUE", "VIRGEN DE LAS LAGRIMAS", "ALICIA MOREAU DE JUSTO", "ALVEAR CARLOS MARIA DE", "ANTONIO MARIA GIANELLI", "CALLE 1 ( BELTRAN BIS)",
        "CALLE 4 - COSTA ALEGRE", "ELISA  ALVEAR DE BOSCH", "FEDERICO RAUCH CORONEL", "CIUDAD DE SAN CAYETANO", "GLORIA TREJON DE LOPEZ", "DIAGONAL BOSQUE GRANDE", "JERONIMO COSTA CORONEL", "JOHN FITZERALD KENNEDY",
        "JOSE EUSEBIO COLOMBRES", "JUAN BAUTISTA AZOPARDO", "JUAN CARLOS CASTAGNINO", "JUAN CONIQUEGUEN YAHAN", "JUAN DE DIOS FILIBERTO", "JUAN MADARIAGA GENERAL", "ESTANISLAO S. ZEBALLOS", "LICIO MANSILLA GENERAL",
        "LOS ALAMOS - BO. CAMET", "MARTINEZ DE HOZ MIGUEL", "LOS CEDROS - BO. CAMET", "PSJE.EL HORNERO-BQ.P.R", "PAZ JOSE MARIA GENERAL", "SUBMARINO ARA SANTA FE", "RUFINO INDA INTENDENTE", "AVENIDA ELIAS ANTUNEZ",
        "ALFREDO MARTINEZ BAYA", "CARLOS SAAVEDRA LAMAS", "CNO. ENTRADA. GAZZOLO", "CNO. EST. CHAPADMALAL", "CNO.NOROESTE LA BOMBA", "DE APARICIO FRANCISCO", "DE LA PLAZA FORTUNATO", "DIAGONAL HOMERO MANZI",
        "DIAGONAL JOSE PEDRONI", "DIAGONAL PLAYA SERENA", "EDUARDO PERALTA RAMOS", "ESTANCIA SAN CIPRIANO", "ESTEBAN ANGEL BONANNI", "PIONERO PETERSEN JUAN", "REFORMA UNIVERSITARIA", "REPUBLICA ARABE SIRIA",
        "PASEO VICTORIA OCAMPO", "AV. DE LOS PESCADORES", "10 DE FEBRERO DE 1874", "AVENIDA DEL HIPODROMO", "ESTANCIA OJO DEL AGUA", "AVENIDA INDEPENDENCIA", "AVENIDA LOS PATAGONES", "232 - BO. V. DE LUJAN",
        "234 - BO. V. DE LUJAN", "B/P DON JOSE MOSCUZZA", "ANGEL PACHECO GENERAL", "EMILIO MARTIN LARRAYA", "CIUDAD DE BRAGADO BIS", "FEDERICO GARCIA LORCA", "FIGUEROA ALCORTA JOSE", "FLORENCIO PARRAVICINI",
        "GONZALEZ SEGURA CESAR", "DIAGONAL BORDE ARROYO", "DIAGONAL CESAR GASCON", "JACINTO PERALTA RAMOS", "JUANA MANUELA GORRITI", "JUAN BAUTISTA ALBERDI", "JUAN F. CZETZ CORONEL", "ESTANCIA LA PEREGRINA",
        "LAVALLE  JUAN GENERAL", "LOPEZ DE GOMARA JUSTO", "LOS COMECHINGONES SUR", "LOS EUCALIPTUS-BQ.P.R", "MARIANO CASTEX DOCTOR", "MARIO RAMON LUNA CABO", "MASCIAS ALBERTO ROQUE", "MAZZA SALVADOR DOCTOR",
        "OTTO KRAUSE INGENIERO", "QUINQUELLA MARTIN BIS", "RAMON CARRILLO DOCTOR", "RIVAS IGNACIO GENERAL", "SANCHEZ LABRADOR R.P.", "SAN FRANCISCO DE ASIS", "12 BIS - LA TRINIDAD", "CARMEN DE LAS FLORES",
        "CONSTANTINO GONZALEZ", "CRUCERO LA ARGENTINA", "DIAGONAL MAR AUSTRAL", "DIAGONAL SAN JACINTO", "DIARTE OSCAR SOLDADO", "DEL CABILDO INDIGENA", "CNO.A.LAS BRUSQUITAS", "HEGUILOR DOMINGO BIS",
        "JOSE ORTEGA Y GASSET", "ESTANCIA CHAPADMALAL", "ESTANCIA EL BOQUERON", "MANUEL QUERINI PADRE", "LA BRAVA - C. VERDES", "PESQUERO PALMA MADRE", "ESTANCIA LA COPELINA", "REMEDIOS DE ESCALADA",
        "REPUBLICA DEL LIBANO", "ARISTOBULO DEL VALLE", "ARTURO PEDRO LUISONI", "ARTURO PERALTA RAMOS", "DE LOS LOBOS MARINOS", "CENTRAL ISLA SOLEDAD", "AVENIDA CONSTITUCION", "JUAN B. JUSTO DOCTOR",
        "AVENIDA RIO COLORADO", "BERNARDO DE IRIGOYEN", "BOULEVARD DEL BOSQUE", "B/P DON TOMAS ROLDAN", "E. SAN ANTONIO ABATE", "B/P ESTRELLA DEL SUR", "CALLE 11 - EL TREBOL", "AMALIA V. DE BALLINA",
        "CALLE 14 - EL TREBOL", "CALLE 16 - EL TREBOL", "CALLE 18 - EL TREBOL", "CALLE 20 - EL TREBOL", "CALLE 22 - EL TREBOL", "CALLE 24 - EL TREBOL", "EDUARDO PEREZ BULNES", "EMMA GEMOLI DE OLIVA",
        "ESCALADA REMEDIOS DE", "JOSE ANTONIO CABRERA", "JUAN FACUNDO QUIROGA", "ESTANISLAO DEL CAMPO", "LISANDRO DE LA TORRE", "MARTIN ALONSO PINZON", "MARTINIANO CHILABERT", "ORIGONE MANUEL FELIX",
        "PASAJE MAR DEL PLATA", "PEDRO Y TADEO FRANCO", "RAMBLA PUNTA MOGOTES", "ROLDAN BELISARIO BIS", "SAN FRANCISCO JAVIER", "SAN JOSE DE CALASANZ", "TORIBIO DE LUZURIAGA", "83 - LOMAS DEL GOLF",
        "ALFREDO L. PALACIOS", "AMERICO RAUL CANOSA", "CARLOS MUJICA PADRE", "CNO.EA. LAS LOMITAS", "CNO. LIMITE NORESTE", "CNO.PIGS-J.B. JUSTO", "CNO.S.DE LOS PADRES", "COLECTORA CALLE 515",
        "COLECTORA NORTE VIA", "DESTRUCTOR HERCULES", "JUSTO ERNESTO ROMAN", "DIAGONAL LOS CURROS", "DIAGONAL PUEYRREDON", "TEODORO J. BRONZINI", "HOLMBERG EDUARDO L.", "HOUSSAY BERNARDO A.",
        "ESTANCIA LA REFORMA", "JOSE IGNACIO THAMES", "JOSE MANUEL ESTRADA", "ESTANCIA LA COLMENA", "MAMERTO ESQUIU FRAY", "PESQUERO HAPPY DAYS", "SANTIAGO DEL ESTERO", "ROMPE HIELOS IRIZAR",
        "ANTARTIDA ARGENTINA", "CENTENO NORBERTO O.", "FERMIN ERREA DOCTOR", "FRANCISCO QUINTEROS", "B/P SAN ANTONINO II", "AVENIDA SANTA MARTA", "BERUTI ANTONIO LUIS", "250 - BO. AUTODROMO",
        "BOULEVARD QUANTEMOC", "B/P LOS TRES AMIGOS", "B/P VICTIMAS DEL 46", "CALLE 1 - EL TREBOL", "663 (LOS CALAMARES)", "CALLE 7 - EL TREBOL", "CALLE 8 - EL TREBOL", "EVA DUARTE DE PERON",
        "FINOCHIETTO ENRIQUE", "FRANCISCO CHACAHUAC", "GUILLERMO VAN HEDEN", "ISLA DE LOS ESTADOS", "ISLAS TULES DEL SUR", "JOAQUIN V. GONZALEZ", "JUAN CARLOS DAVALOS", "ESTANCIA LA ARMONIA",
        "LOS CIPRECES-BQ.P.R", "LOS CLAVELES-BQ.P.R", "MACEDONIO FERNANDEZ", "MAC GAUL ANDRES BIS", "TERMAS DE RIO HONDO", "MARCELINO ECHEGARAY", "MIGUEL GUGLIELMOTTI", "MIGUEL SAGASTIZABAL",
        "PASAJE BANAT GABITO", "PASAJE SAN BERNARDO", "PSJE.BERUTI ANTONIO", "13 BIS-LA TRINIDAD", "1 - CNIA. BARRAGAN", "4 - CNIA. BARRAGAN", "CASTELLI JUAN JOSE", "CAYETANO RODRIGUEZ",
        "CEFERINO NAMUNCURA", "COMODORO RIVADAVIA", "CONRADO NALE ROXLO", "CORONEL SUAREZ BIS", "DE LOS ESPAÑOLES B", "DE LOS INMIGRANTES", "DE LOS RESERVISTAS", "CERRO SAN VALENTIN",
        "SANTA ROSA DEL MAR", "DIECKMANN JUANA G.", "CERVANTES SAAVEDRA", "HARAS LA MADRUGADA", "HECTOR BORDON CABO", "ESQUIVEL EMILIO J.", "ESTANCIA LA CORONA", "HEROES DE MALVINAS",
        "PESQUERO QUO VADIS", "REMOLCADOR GUARANI", "SANTIAGO CASABRUNA", "11 BIS-LA TRINIDAD", "AVELLANEDA NICOLAS", "AVENIDA JUAN CUTAY", "AVENIDA PEDRO LURO", "VICTORIO TETAMANTI",
        "BAUTISTA ALBERVIDE", "BAUTISTA MENDIOROZ", "VIRGEN DEL ROSARIO", "AMBROSETTI JUAN B.", "BORDEU JUAN MANUEL", "2 - CNIA. BARRAGAN", "3 - CNIA. BARRAGAN", "5 - CNIA. BARRAGAN",
        "9 -EST.CHAPADMALAL", "ALVARADO RUDECINDO", "ANGEL ROFFO DOCTOR", "ANTONIO A. VIGNOLO", "VUELTA DE OBLIGADO", "3 (GODOY CRUZ BIS)", "CHUYANTUYA CACIQUE", "CIANCHETTA LORENZO",
        "FRENGUELLI JOAQUIN", "GAMAL ABDEL NASSER", "GODOFREDO DAIREAUX", "JOSE ADRIAN BOTANA", "JOSE CARDIEL PADRE", "JOSÉ FERRARI OCAÑA", "JUAN A CASACUBERTA", "ESTANCIA ITUZAINGO",
        "JUAN NESTOR GUERRA", "ESTEBAN ECHEVERRIA", "LUIS VARETTO PADRE", "MAGRASSI GUILLERMO", "ONESIMO LEGUIZAMON", "OLEGARIO V ANDRADE", "PSJE.GARDEL CARLOS", "PEDRO MIGUEL ARAOZ",
        "VALENTIN SAYHUEQUE", "AGUSTIN RODRIGUEZ", "ALBERTO DEL SOLAR", "ALMONACID VICENTE", "9 -  COSTA ALEGRE", "CARLOS PELLEGRINI", "CATALINA DAPROTIS", "CATRIEL CIRPRIANO",
        "CNO.CNIA BARRAGAN", "CNO. CONSTITUCION", "CNO.URANGA HELMER", "COMUNA DE MAFALDA", "CONCEPCION ARENAL", "CORBETA GRANVILLE", "D´ARTAGNAN LOHIOL", "DE LA INMIGRACION",
        "DE LAS OLIMPIADAS", "DE LOS MISIONEROS", "DE LOS PEREGRINOS", "DE LOS PESCADORES", "DE MARCHI ANTONIO", "SANTANGELO INVADO", "DOLORES MEMBRIVES", "EDUARDO G. CARASA",
        "CIUDAD DE BRAGADO", "HARAS EL VENCEDOR", "HARAS LAS ORTIGAS", "HORACIO ENGLENDER", "DIAGONAL CALLE 14", "DIAGONAL CALLE 48", "DIAGONAL CALLE 50", "DIAGONAL CALLE 66",
        "DIAGONAL CALLE 68", "GOYENECHE ROBERTO", "LUIS BELTRAN FRAY", "HIPOLITO BOUCHARD", "HELMER URANGA BIS", "MANUEL BAIGORRITA", "KRAGLIEVICH LUCAS", "REP. DE NICARAGUA",
        "REPUBLICA DE CUBA", "RICARDO GUIRALDES", "RICARDO GUTIERREZ", "JESUS DE GALINDEZ", "VICENTE LABORANTE", "ROSALIA DE CASTRO", "ANTONIO VALENTINI", "ARROYO CORRIENTES",
        "AUTOPISTA 705 BIS", "AVENIDA LAS TALAS", "BALTAZAR DEMATTEI", "BAUTISTA LAUREANO", "DON JOSE MOSCUZZA", "V.M.TERESA MICHEL", "BURMEISTER GERMAN", "54-BO.EL BOQUERON",
        "ALEJANDRO FLEMING", "ALVAREZ FRANCISCO", "B/P SAN FRANCISCO", "1 -  COSTA ALEGRE", "2 -  COSTA ALEGRE", "3 -  COSTA ALEGRE", "5 -  COSTA ALEGRE", "6 -  COSTA ALEGRE",
        "7 -  COSTA ALEGRE", "8 -  COSTA ALEGRE", "EL GALLEGO MANUEL", "EL MANUELIN TRUCO", "EL RUBIO FEDERICO", "EUSEBIONE LORENZO", "EVARISTO CARRIEGO", "EX CAMINO MIRAMAR",
        "CIUDAD DE DOLORES", "FERNANDO CATUOGNO", "FLORENCIO SANCHEZ", "CIUDAD DE ONEGLIA", "CIUDAD DE ROSARIO", "FLORISBELO ACOSTA", "FRAGATA MALDONADO", "FRAGATA SARMIENTO",
        "FRANCISCO ALVAREZ", "FRANCISCO PIZARRO", "FRANCISCO SARTORA", "FURLONG GUILLERMO", "GARAGIOLA ALBERTO", "GIACOMO MATTEOTTI", "DIAGONAL CALLE 42", "DIAGONAL CALLE 44",
        "DIAGONAL CALLE 46", "GUERRICO ANATILDO", "DIAGONAL CALLE 52", "DIAGONAL CALLE 54", "CORTADA DEL TANGO", "JUANA AZURDUY BIS", "TOMAS ALVA EDISON", "JUAN N. FERNANDEZ",
        "LEOPOLDO MARECHAL", "HIPOLITO YRIGOYEN", "MATIENZO BENJAMIN", "MIGUEL DE UNAMUNO", "OLAZABAL FELIX DE", "PSJE.ERREA FERMIN", "PTA. RAMOS E. BIS", "PTA.RAMOS EDUARDO",
        "VILLARINO BASILIO", "RUTA NACIONAL N 2", "SAAVEDRA CORNELIO", "AMBROSIO BESTOSO", "CAMET JUAN PEDRO", "CELEDONIO FLORES", "CELESTINO GALDOS", "CERRO CAMPANARIO",
        "DARREGUEYRA JOSE", "DE LOS ESPA?OLES", "DE LOS ITALIANOS", "DE LOS JUBILADOS", "DEL PUEBLO PAMPA", "DIAGONAL 709 BIS", "LEOPOLDO LUGONES", "OVIDIO ZUBIAURRE",
        "CERRO MERCEDARIO", "DOMINGO HEGUILOR", "TEODORO BRONZINI", "HARAS FIRMAMENTO", "HARAS LA BIZNAGA", "HEGUILOR DOMINGO", "DIAGONAL 711 BIS", "JOSE ROGER BALET",
        "LUIS ANGEL FIRPO", "PESQUERO KONTIKI", "PAULA ALBARRACIN", "SANTIAGO LACAMTU", "ROQUE SAENZ PEÑA", "10 - ARROYO SECO", "AVENIDA DIAGONAL", "JUAN HECTOR JARA",
        "AVENIDA LIBERTAD", "PRESIDENTE PERON", "VICTORIO FAGNANI", "BAUTISTA BALERDI", "BELISARIO ROLDAN", "BORDABEHERE ENZO", "DON TOMAS ROLDAN", "ESTRELLA DEL SUR",
        "B/P IVONNE MARTA", "54 - EL BOQUERON", "ALFONSINA STORNI", "ALBERTO EINSTEIN", "ALEJANDRO AGUADO", "ANTONIO SPINELLI", "ANTONIO STROPATO", "1 ( BELTRAN BIS)",
        "4 - COSTA ALEGRE", "TAYCHOCO CACIQUE", "CESAR A. CERETTI", "EL ZORRINO ROJAS", "ENRRIQUE LARRETA", "FEDERICO SERRANO", "FIGUEROA ALCORTA", "FRAGATA LIBERTAD",
        "FRANCISCO CANARO", "FRANCISCO FERRER", "GABRIELA MISTRAL", "GENARO GIACOBINI", "GERTRUDIS-BQ.P.R", "GRIERSON CECILIA", "INDIOS ARAUCANOS", "IRALA DOMINGO DE",
        "DIAGONAL CENTRAL", "ELPIDIO GONZALEZ", "JOAQUINA ACEVEDO", "JOSE DE LA LLOSA", "JOSE DUTTO PADRE", "ESTADO DE ISRAEL", "JUAN JOSE PEREDA", "LAS LAMBERCIANAS",
        "LAS LAMBERTIANAS", "LEBENSOHN MOISES", "LEONARDO ROSALES", "LORENZINI CAROLA", "HERMINIA BRUMANA", "HNOS FRASCAROLIO", "TIERRA DEL FUEGO", "MARTINEZ ANTONIO",
        "LAHILLE FERNANDO", "OSVALDO MAGNASCO", "PAJARITO PEREYRA", "PASAJE DE ANGELI", "PASCUAL MUGABURU", "PSJE.EL CARDENAL", "RODRIGUEZ MARTIN", "SALVADOR ALLENDE",
        "ROTONDA DEL LAGO", "TOMAS GODOY CRUZ", "TOMAS STEGAGNINI", "VALENTIN VERGARA", "WILLIAN C MORRIS", "1 - ARROYO SECO", "67 - NUEVO GOLF", "ADOLFO E DAVILA",
        "AGUSTIN MAGALDI", "ALEJANDRO VOLTA", "CAMET FLORENCIO", "VIEJO A MIRAMAR", "SCAGLIA LORENZO", "CANDELARIA LUIS", "CANGAPOL-BQ.P.R", "CATULO CASTILLO",
        "SCIOCCO DOMINGO", "SEBASTIAN GARAU", "CNO.A LOS PATOS", "CERRO ACONCAGUA", "CORBETA URUGUAY", "COSTA ATLANTICA", "CRAMER AMBROSIO", "DAGLIO CAYETANO",
        "DANTE ALIGHIERI", "DE LA REDUCCION", "DE LAS CARRETAS", "DE LOS JESUITAS", "DE ROSAS JUAN M", "HORACIO QUIROGA", "EDUARDO BRADLEY", "CASTILLA Y LEON",
        "CERRO ACONQUIJA", "HARAS EL CANDIL", "HARAS HORIZONTE", "HARAS MALAL HUE", "HORACIO GAUDINI", "HUGO DEL CARRIL", "JOSE INGENIEROS", "JOSE LIJO LOPEZ",
        "LUIS DELLEPIANE", "MAIZANI AZUCENA", "MANUELA PEDRAZA", "PESQUERO HALCON", "PESQUERO NARWAL", "PESQUERO NOMADE", "PESQUERO PUMARA", "LOS CHIRIGUANOS",
        "SILVESTRE TOHEL", "RIO DE LA PLATA", "VICTORIA OCAMPO", "PDO. DE LOBERIA", "SANTIAGO CAYADO", "SANTIAGO DANERI", "SANTIAGO SASTRE", "TRINIDAD TOBAGO",
        "ASTOR PIAZZOLLA", "DE LA HERRADURA", "11 DE SETIEMBRE", "SAN ANTONINO II", "ROBERTO J PAYRO", "VIDAL CELESTINO", "AZUCENA MAIZANI", "VIGNOLO ANTONIO",
        "BENEDETTO CROCE", "20 DE SETIEMBRE", "VIRREY DEL PINO", "BORMIDA MARCELO", "LOS TRES AMIGOS", "B/P SAN GABRIEL", "VICTIMAS DEL 46", "BROWN ALMIRANTE",
        "CABO CORRIENTES", "CABRAL SARGENTO", "CALABRESE ENEAS", "6 - ARROYO SECO", "8 - ARROYO SECO", "CALLE 120 BATAN", "ANDRES MAC GAUL", "ANGELONA PAGANO",
        "ANTONIO MACHADO", "CIOCCHINI CLETO", "GUTENBERG BIS B", "FELIPE DE ARANA", "FERNANDO BONNET", "CLEMENTE CAYROL", "FRESEDO OSVALDO", "GALEANA ANTONIO",
        "GONZALEZ CHAVEZ", "GREGORIO GOROZO", "INDA RUFINO BIS", "ISLA CANDELARIA", "ISLA CORONACION", "ISLA DE CERDEÑA", "JOSE DOCNOYAHAL", "JUAN JOSE VALLE",
        "LAS MADREPERLAS", "LAS TRES MARIAS", "LEANDRO N. ALEM", "LEONCIO CAMARGO", "LEOPOLDO MENDEZ", "LOS BAQUEANOS B", "LOS CRISANTEMOS", "ESTRELLA DE MAR",
        "MANUEL QUINTANA", "MARIQUE CACIQUE", "LA CRUZ DEL SUR", "MENGHIN EDUARDO", "MITRE BARTOLOME", "MONTE MALABRIGO", "NEWBERY EDUARDO", "OLEGARIO OLAZAR",
        "ORTIZ DE ZARATE", "OSVALDO FRESEDO", "PASAJE CALLE 46", "PASAJE CATEDRAL", "PASAJE EL DANTE", "PSJE.EL HORNERO", "RAFAEL OBLIGADO", "RIO SAMBOROMBON",
        "SANTOS BAÑUELOS", "SACACHU CACIQUE", "TOMAS YEMEHUECH", "13-LA TRINIDAD", "16-LA TRINIDAD", "CARLOS TEJEDOR", "CASILDO VILLAR", "CNO. EST. COBO",
        "CNO. RIO PINTO", "SERRANO JOSE M", "COSTA PAMPEANA", "CERRO FITZ ROY", "CRUZ DEL NORTE", "DE LA ENRAMADA", "DIAGONAL NORTE", "CERRO MURALLON",
        "DONATO ALVAREZ", "EDUARDO AROLAS", "SIERRA DE PUAN", "CERRO TRONADOR", "EDUARDO MALLEA", "CHANAL CACIQUE", "CERRO FIAMBALA", "CIUDAD DE ROMA",
        "GUTENBERG JUAN", "HARAS ABOLENGO", "HARAS ALFALFAR", "HARAS VOCACION", "JOSE LANZILOTA", "JOSE ZACAGNINI", "LOS TEHUELCHES", "PLACIDO GARCIA",
        "RIO MIRAFLORES", "ROCAS CORMORAN", "RICARDO BALBIN", "RINGUELET RAUL", "RIO CANDELARIA", "URQUIA SERAPIO", "B/P MARILUZ II", "ARMANDO CHULAK",
        "10-LA TRINIDAD", "11-LA TRINIDAD", "FELIX U. CAMET", "JUAN JOSE PASO", "12-LA TRINIDAD", "14-LA TRINIDAD", "15-LA TRINIDAD", "AVENIDA VERTIZ",
        "AYESA FELIX DE", "17-LA TRINIDAD", "BOMPLAND AMADO", "B/P CAMPANELLO", "CALABRIA BIS B", "11 - EL TREBOL", "VOLCAN COPAHUE", "ALFREDO LEPERA",
        "AGUSTIN VILERT", "ALBERTI MANUEL", "ALEJANDRO KORN", "14 - EL TREBOL", "ANGEL GARDELLA", "16 - EL TREBOL", "18 - EL TREBOL", "20 - EL TREBOL",
        "22 - EL TREBOL", "24 - EL TREBOL", "CALLE 39 BIS B", "EL MIRADOR BIS", "EL MISO ZAMORA", "EL TANO TIZONE", "EMILIO SALGARI", "FELIX DE AYALA",
        "FERNANDEZ JUAN", "FRAGATA HALCON", "FRENCH DOMINGO", "FUNES GREGORIO", "GALLARDO ANGEL", "GANDHI MAHATMA", "GERONIMO REJON", "GOLETA SARANDI",
        "GRANJA MARUCHA", "ISLA DE BORBON", "ISLA DE ISCHIA", "ISLA JOINVILLE", "ISLA REMOLINOS", "ISLAS BALEARES", "JOSE DEYACOBBI", "JOSE GARIBALDI",
        "JOSE HERNANDEZ", "JUAN CALCHAQUI", "JUAN D`ARIENZO", "JUAN GUTENBERG", "LAS CASUARINAS", "LAS CORTADERAS", "LAS GALLARETAS", "LAS HORTENSIAS",
        "LAS MARAVILLAS", "LAS MARGARITAS", "LIBRES DEL SUR", "LOMAS DEL GOLF", "LOS ALGARROBOS", "ESTEBAN GASCON", "LOS DURAZNEROS", "LOS EUCALIPTOS",
        "LOS EUCALIPTUS", "LOS HIPOCAMPOS", "LOS MEJILLONES", "LOS QUEBRACHOS", "LOS QUERANDÍES", "HNOS ALDACOCHE", "MACACHA GUEMES", "JULIAN AGUIRRE",
        "JULIO CORTAZAR", "MATHEU DOMINGO", "MATIAS STROBEL", "MIGUEL URRUTIA", "MIGUEL VIGNOLO", "PARODI LORENZO", "PASAJE EL FARO", "PASCANA GRANDE",
        "PSJE.EL ZORZAL", "PSJE. PORTUGAL", "PSJE.VENEZUELA", "RAMON ITURRIOZ", "PEDRO IRIGOYEN", "RODRIGUEZ PEÑA", "ROMERO EDUARDO", "SOUESSIA ISAAC",
        "SUAREZ CORONEL", "VECINOS UNIDOS", "VELEZ GREGORIO", "ELIAS ANTUNEZ", "3-LA TRINIDAD", "7-LA TRINIDAD", "9-LA TRINIDAD", "CARLOS GARDEL",
        "CARLOS PIGOZI", "CNO.EL TEJADO", "CNO.EST CAMET", "CALLE 248 BIS", "CNO.STA PAULA", "COMECHINGONES", "CERRO HERMOSO", "CURA BROCHERO",
        "DEL CORRALERO", "MANUEL CANATA", "MAR DEL PLATA", "DIAGONAL OMBU", "RENE FAVALORO", "SANTA CECILIA", "DOMINGO BATAN", "EA. SAN JUSTO",
        "CHILABERT BIS", "HAENCKE TADEO", "HARAS COMALAL", "HARAS EL TURF", "ATLANTICO SUR", "LAS NAZARENAS", "HERNAN CORTES", "LOS TULIPANES",
        "LUCIANO ARRUE", "HELMER URANGA", "CALLE 697 BIS", "MANUEL BLANCO", "MANUEL GRANDE", "LA GOLONDRINA", "GUTENBERG BIS", "LOS CHIMANGOS",
        "LOS CARRUAJES", "REGION MOLISE", "REPUBLIQUETAS", "RICARDO PALMA", "RICARDO ROJAS", "RIO CALCHAQUI", "RIO CARCARAÑA", "RIO CORCOVADO",
        "RIO FELICIANO", "RIO GUALEGUAY", "RIO LAS LAJAS", "HIPOLITO SOSA", "PEDRO BOUCHEZ", "PEDRO DEJORGE", "VICENTE LOPEZ", "VILLA GUSTAVA",
        "ARANA Y GOIRI", "AVENIDA COLON", "DEL HIPODROMO", "INDEPENDENCIA", "12 DE OCTUBRE", "LOS PATAGONES", "VIOLETA PARRA", "BENITO JUAREZ",
        "1-LA TRINIDAD", "BORTHABURU A.", "ABDALA GERMAN", "B/P SHERIFF 1", "5-LA TRINIDAD", "CABRERA ANGEL", "6-LA TRINIDAD", "8-LA TRINIDAD",
        "AMADEO COUREL", "ANTONIO ALICE", "ANTONIO SAENZ", "SAN FRANCISCO", "1 - EL TREBOL", "CALLE 431 BIS", "CALLE 427 BIS", "CALLE 429 BIS",
        "CALLE 433 BIS", "TAVELLI PABLO", "CALLE 507 BIS", "CALLE 513 BIS", "CALLE 687 BIS", "TAPIA AUGUSTO", "CALLE 719 BIS", "CALLE 771 BIS",
        "LA PASIONARIA", "CALLE 791 BIS", "CALLE 793 BIS", "7 - EL TREBOL", "CALLE 801 BIS", "CALLE 819 BIS", "CALLE 823 BIS", "8 - EL TREBOL",
        "EDUARDO WILDE", "EL CARPINTERO", "EL CHURRINCHE", "EL EMPRENDADO", "EUSEBIO BLANC", "FAUSTINO NUÑO", "FRAGATA ITATI", "GARAY JUAN DE",
        "GO?I JUAN BIS", "GROEBER PABLO", "BOSQUE GRANDE", "ISLA ELEFANTE", "ISLA SEBALDES", "ISLA TRAVERSE", "ISLA TRINIDAD", "JORGE CAFRUNE",
        "JUANA AZURDUY", "JUAN FERMINIA", "JUAN JAUREGUI", "JUAN VUCETICH", "LAS CABRILLAS", "LAS CARACOLAS", "LAS CENTOLLAS", "LAS GARDENIAS",
        "LAS GROSELLAS", "LAS MAGNOLIAS", "LAS PALOMETAS", "LAS TIJERETAS", "LEON FRAGNAUD", "LOS ALMENDROS", "LOS ARRAYANES", "LOS AVELLANOS",
        "LOS BAQUEANOS", "LOS CALAMARES", "LOS DIAGUITAS", "LOS GLADIOLOS", "LOS GUARANIES", "LOS INCIENSOS", "LOS LIMONEROS", "LOS MOHICANOS",
        "LOS PALENQUES", "LOS RANQUELES", "LUIS SANDRINI", "JULIO CANESSA", "JULIO DE CARO", "MARCOS SASTRE", "MARIANO ROSAS", "MARTIN FIERRO",
        "MARTIN OVIEDO", "TIERRA GAUCHA", "MORENO PERITO", "MOYANO CARLOS", "NICOLAS DAZEO", "PRIMERA JUNTA", "PSJE. ECUADOR", "PUERTO MADRYN",
        "RAFAEL GARCIA", "RAMON CABEZAS", "RIO PILCOMAYO", "RIO TUPUNGATO", "RODOLFO WALSH", "PEDRO FERRARI", "PEDRO GUILLEN", "PEDRO MEDRANO",
        "ROMANO NESTOR", "SALVADOR VIVA", "TOMAS FALKNER", "VICENTE CUELI", "CARLOS BERRA", "CARLOS MELGA", "CNO.EL CASAL", "CNO.EST COBO",
        "CALLE 12 BIS", "CNO.RUTA 226", "CERRO FATIMA", "DE LOS INCAS", "DIAGONAL  41", "DIAGONAL 707", "DIAGONAL 709", "DIAGONAL 711",
        "HOMERO MANZI", "JOSE PEDRONI", "PLAYA SERENA", "CERRO NEVADO", "DIAGONAL SUR", "CALLE 67 BIS", "IGNACIO OLAN", "JOSE RAZZANO",
        "HERNANDARIAS", "LOS ZORZALES", "LUCIO VARELA", "LUIS DEL ORO", "LA CALANDRIA", "LOS CHAÑARES", "LOS CIPRECES", "LOS CASTAÑOS",
        "RIO CEBALLOS", "RIO GALLEGOS", "SAN PATRICIO", "SAN SALVADOR", "TRES ARROYOS", "AVENIDA ABEL", "CONSTITUCION", "RIO COLORADO",
        "BAHIA BLANCA", "BAHÍA THETIS", "VIÑA DEL MAR", "BENITO LINCH", "NUEVO BOSQUE", "IVONNE MARTA", "BUENOS AIRES", "CALLE 69 BIS",
        "3 DE FEBRERO", "CALABRIA BIS", "CALASANZ BIS", "CALLE 10 BIS", "CALLE 14 BIS", "CALLE 27 BIS", "CALLE 22 BIS", "CALLE 28 BIS",
        "CALLE 30 BIS", "CALLE 32 BIS", "CALLE 34 BIS", "CALLE 36 BIS", "CALLE 39 BIS", "CALLE 33 BIS", "CALLE 40 BIS", "CALLE 41 BIS",
        "CALLE 45 BIS", "CALLE 48 BIS", "CALLE 63 BIS", "CALLE 65 BIS", "CALLE 86 BIS", "CALLE 89 BIS", "EL AMERICANO", "EL CORBATITA",
        "ELIAS ALIPPI", "EL MANANTIAL", "EL MANGRULLO", "EL TERU TERU", "GERTRUDIS M.", "BORDE ARROYO", "ISLA PAJAROS", "ISLA SOLEDAD",
        "CESAR GASCON", "JORGE AVALOS", "JUAN A. PEÑA", "JUAN B. GOÑI", "JUAN LABORDE", "JUAN MARIANI", "LA MARTINETA", "LA PRIMAVERA",
        "LA QUERENCIA", "LAS ALAMEDAS", "LAS AZUCENAS", "LAS BALLENAS", "LAS CAMELIAS", "LAS CHARITAS", "LAS CORVINAS", "LAS HIGUERAS",
        "LAS PALMERAS", "LAS TORTUGAS", "LAS VIOLETAS", "LA TORCACITA", "LOS ABEDULES", "LOS ABIPONES", "LOS ARENQUES", "LOS ARRIEROS",
        "LOS CANDILES", "LOS CARDALES", "LOS CIRUELOS", "LOS CLAVELES", "LOS DELFINES", "LOS GERANIOS", "LOS GRANADOS", "LOS HALCONES",
        "LOS HELECHOS", "LOS JACINTOS", "LOS JAZMINES", "LOS MALVONES", "LOS MANZANOS", "LOS MAPUCHES", "LOS MINUANES", "LOS MOCORETA",
        "LOS NARANJOS", "LOS NARVALES", "LOS NAUTILUS", "LOS OLIVARES", "LOS PARAISOS", "LOS PEÑASCOS", "LOS PLATANOS", "LOS PLATEROS",
        "LOS SALMONES", "LUIS VARESSE", "MONTE OLIVIA", "NAHUEL HUAPI", "PABLO NERUDA", "PURA SAGASTA", "QUESADA JOSE", "RAFAEL LATUF",
        "ROBERTO ARLT", "PEDRO GOYENA", "SOLER MIGUEL", "STELLA MARIS", "SAGASTA PURA", "128 - BATAN", "22 DE ABRIL", "AGUA BLANCA",
        "SICILIA BIS", "CNO.MARAYUI", "CERRO ADELA", "DARDO ROCHA", "SEVERO RUIZ", "MAR AUSTRAL", "SAN JACINTO", "CERRO PAINE",
        "CALLE 695 B", "CERRO LANIN", "CERRO TORRE", "JOSE MARMOL", "JOSE PANTEA", "JOSE YAHATY", "LOS TILOS B", "LUIS FRANCO",
        "LUIS LELOIR", "MANCU COPAC", "JULIAN RIOS", "JULIO VERNE", "LOS CEREZOS", "RIO MATANZA", "RIO AGUAPEY", "RIO BERMEJO",
        "RIO COSQUIN", "SAN LORENZO", "SANTA ELENA", "TRIUNVIRATO", "TUPAC-AMARU", "BLAS PARERA", "ARTURO ALIO", "AVALOS JUAN",
        "B/P PAMPERO", "AVENIDA LIA", "B/P PIONERO", "14 DE JULIO", "SANTA MARTA", "BOSCH ELISA", "B/P DORREGO", "SAN GABRIEL",
        "BRAVO MARIO", "CALCHAQUIES", "CALLE 0 BIS", "CALLE 2 BIS", "CALLE 4 BIS", "CALLE 6 BIS", "CALLE 8 BIS", "EL BENTEVEO",
        "EL CENCERRO", "EL CHINGOLO", "EL COLMENAR", "EL FLAMENCO", "EL GAVIOTIN", "CHAPADMALAL", "EL JILGUERO", "EL LEÑATERO",
        "EL PEJERREY", "EL PICAFLOR", "EL PIRINCHO", "EL TORDILLO", "FERRE PEDRO", "GUIDO TOMAS", "ISLA BLANCO", "ISLA LAURIE",
        "JOSE ALONSO", "JUANA MANSO", "LA QUEBRADA", "LA RATONERA", "LAS ACACIAS", "LAS ALMEJAS", "LAS AZALEAS", "LAS ENCINAS",
        "LA SERRANIA", "LAS FRECIAS", "LAS MORERAS", "LAS NUTRIAS", "LAS RETAMAS", "LAS TONINAS", "LAS TOTORAS", "LA TIJERETA",
        "LA TROPILLA", "LOS ALELIES", "LOS AZTECAS", "LOS CORALES", "LOS FOGONES", "LOS FRESNOS", "LOS MATACOS", "LOS MIMBRES",
        "LOS NOGALES", "LOS PERALES", "LOS QUILMES", "LUIS VERNET", "JULIO MUÑOZ", "LA CACHIRLA", "MARIE CURIE", "MARIO BRAVO",
        "MIGUEL CANE", "OUTES FELIX", "PABON PEDRO", "RAMON ARVES", "RIO TERCERO", "PEDRO FERRE", "SAN ANTONIO", "SANAVIRONES",
        "RUBEN DARIO", "VALLE VERDE", "VAN HEDEN G", "YAHATY JUAN", "ZANNI PEDRO", "CALLE 14 B", "CAMPESINOS", "CAMPO FLOR",
        "CANAI QUEN", "ARQ.CEDRON", "CALLE 13 B", "CAUPOLICAN", "CEDRO AZUL", "CALLE 20 B", "CERRO AZUL", "CORRIENTES",
        "COSTA AZUL", "CURRUNAHEL", "DEL ALJIBE", "DEL LUCERO", "LOS CURROS", "PUEYRREDON", "DON ORIONE", "HNOS SMITH",
        "JOSE MARTI", "LUIS AGOTE", "PESCADORES", "PLUS ULTRA", "LOS CEIBOS", "RIO BLANCO", "RIO CURACO", "RIO JACHAL",
        "SAN MARTIN", "SANTA CRUZ", "SANTA INES", "SANTA ROSA", "MARILUZ II", "B/P MARLIN", "JUAN CUTAY", "PEDRO LURO",
        "DEL BOSQUE", "B/P ALTAIR", "CAMPANELLO", "B/P FOCA B", "25 DE MAYO", "CALAZA BIS", "9 DE JULIO", "CALLE 10 B",
        "CALLE 11 B", "CALLE 12 B", "ALMAFUERTE", "CALLE 15 B", "CALLE 16 B", "CALLE 17 B", "CALLE 18 B", "CALLE 19 B",
        "CALLE 22 B", "CALLE 23 B", "CALLE 24 B", "CALLE 25 B", "CALLE 27 B", "CALLE 30 B", "CALLE 31 B", "CALLE 53 B",
        "CALLE 55 B", "CALLE 56 B", "EL ESTRIBO", "EL GORRION", "EL HORNERO", "CHAMPAGNAT", "EL MILAGRO", "EL MIRADOR",
        "EL PAMPERO", "EL REMANSO", "EL ROSILLO", "EL TAJAMAR", "EL TOBIANO", "ENTRE RIOS", "GENOVA BIS", "GOLONDRINA",
        "GUAYCURUES", "ISLA VIGIA", "LAS DALIAS", "LA SERRANA", "LAS FRESAS", "LAS OSTRAS", "LA TORCAZA", "LA VAGUADA",
        "LA VIHUELA", "LILLO LUIS", "LOS ABETOS", "LOS ALAMOS", "LOS APEROS", "LOS AROMOS", "LOS JUNCOS", "LOS LIRIOS",
        "LOS MIRLOS", "LOS NARDOS", "LOS OMBUES", "LOS ROBLES", "LOS SAUCES", "MAGALLANES", "LA ALONDRA", "LA CIGUEÑA",
        "LA GAVIOTA", "MIGUELETES", "NEWBERY J.", "PAGO CHICO", "LOS CEDROS", "PUJIA JOSE", "RIO NOGOYA", "RIO PARANA",
        "RIO SUQUIA", "ROCA JULIO", "SAN BENITO", "TALCAHUANO", "YANQUETRUZ", "YAPEYU BIS", "CALLE 9 B", "CALLE 9 C",
        "SEMBRADOR", "CATAMARCA", "COLECTORA", "CALLE 455", "DEL TEJAR", "CALLE 497", "CALLE 4 B", "CALLE 509",
        "CALLE 719", "CALLE 693", "DON BOSCO", "CALLE 6 B", "CALLE 697", "LOS TILOS", "CALLE 236", "JURAMENTO",
        "LA AGUADA", "LA LAGUNA", "RAUCH BIS", "PATAGONES", "RIO ATUEL", "RIO BELEN", "RIO DULCE", "CALLE 136",
        "PATAGONIA", "SAN PEDRO", "VALENTINA", "ARAUCANOS", "ARGENTINA", "ARRIBE?OS", "ATAHUALPA", "AVENIDA 7",
        "AVENIDA 8", "LAS TALAS", "CALLE 238", "CALLE 699", "AZCUENAGA", "1 DE MAYO", "QUANTEMOC", "SHERIFF 1",
        "CALFUCURA", "CALLE 204", "CALLE 206", "CALLE 101", "CALLE 103", "CALLE 105", "CALLE 107", "CALLE 208",
        "120 BATAN", "CALLE 128", "CALLE 142", "CALLE 159", "CALLE 160", "CALLE 194", "CALLE 196", "CALLE 198",
        "CALLE 1 B", "CALLE 1 C", "CALLE 200", "CALLE 202", "CALLE 228", "CALLE 2 B", "CALLE 2 C", "CALLE 3 B",
        "CALLE 3 C", "CALLE 429", "CALLE 445", "CALLE 447", "CALLE 449", "CALLE 451", "CALLE 453", "CALLE 457",
        "CALLE 459", "CALLE 461", "CALLE 463", "CALLE 465", "CALLE 467", "CALLE 471", "CALLE 473", "CALLE 475",
        "CALLE 477", "CALLE 479", "CALLE 481", "CALLE 483", "CALLE 485", "CALLE 487", "CALLE 489", "CALLE 491",
        "CALLE 493", "CALLE 495", "CALLE 499", "CALLE 4 C", "CALLE 501", "CALLE 503", "CALLE 505", "CALLE 507",
        "CALLE 511", "CALLE 513", "CALLE 5 B", "CALLE 5 C", "CALLE 797", "CALLE 6 C", "CALLE 701", "CALLE 703",
        "CALLE 705", "CALLE 713", "CALLE 715", "CALLE 717", "CALLE 7 B", "CALLE 721", "CALLE 723", "CALLE 725",
        "CALLE 727", "CALLE 729", "CALLE 731", "CALLE 733", "CALLE 735", "CALLE 737", "CALLE 739", "CALLE 741",
        "CALLE 743", "CALLE 745", "CALLE 747", "CALLE 749", "CALLE 751", "CALLE 753", "CALLE 755", "CALLE 757",
        "CALLE 759", "CALLE 761", "CALLE 763", "CALLE 765", "CALLE 767", "CALLE 769", "CALLE 771", "CALLE 773",
        "CALLE 775", "CALLE 777", "CALLE 779", "CALLE 781", "CALLE 783", "CALLE 785", "CALLE 787", "CALLE 789",
        "CALLE 791", "CALLE 793", "CALLE 795", "CALLE 799", "CALLE 801", "CALLE 803", "CALLE 805", "CALLE 807",
        "CALLE 809", "CALLE 811", "CALLE 813", "CALLE 815", "CALLE 817", "CALLE 819", "CALLE 821", "CALLE 823",
        "CALLE 825", "CALLE 827", "CALLE 829", "CALLE 831", "CALLE 833", "CALLE 835", "CALLE 837", "CALLE 839",
        "CALLE 841", "CALLE 843", "CALLE 845", "CALLE 847", "CALLE 849", "CALLE 851", "CALLE 853", "CALLE 8 B",
        "EL ALAZAN", "EL HORCON", "CHACABUCO", "EL JAGUEL", "EL RECADO", "EL RINCON", "EL TEJADO", "EL ZORZAL",
        "ESPIGON 3", "FLORENCIA", "FLORENCIO", "FRANCISCA", "FRANCISCO", "GERTRUDIS", "GO?I JUAN", "GUANAHANI",
        "GUILLERMO", "INCA HUEN", "ITUZAINGO", "ESPIGON 7", "JUAN ACHA", "LA PERDIZ", "LA LOMADA", "LA MATERA",
        "LAS CALAS", "LAS FOCAS", "LAS HAYAS", "LAS HERAS", "LAS LISAS", "LAS LOMAS", "LAS ORCAS", "LAS ROSAS",
        "LA SURE?A", "LOMBARDIA", "LOS ARCES", "LOS INCAS", "RIO LIMAY", "LOS OLMOS", "LOS ORTIZ", "LOS PINOS",
        "LOS TAPES", "LA AURORA", "MARGARITA", "ORO NEGRO", "RIO LULES", "LA COLINA", "LA CUESTA", "MOCTEZUMA",
        "NAHUELPAN", "NAMUNCURA", "NATIVIDAD", "O'HIGGINS", "OLAVARRIA", "PALESTINA", "RIO NEGRO", "RIO PINTO",
        "RIO TEUCO", "RIVADAVIA", "SARMIENTO", "VENEZUELA", "AGUATERO", "AMEGHINO", "CALLE 91", "CALLE 93",
        "CALLE 94", "CALLE 95", "CALLE 97", "CALLE 99", "CANGAPOL", "CARDENAL", "CATALUÑA", "CALLE 14",
        "CALLE 22", "CNO.PIGS", "COLIQUEO", "COLOMBIA", "CALLE 21", "CALLE 28", "CALLE 29", "CALLE 30",
        "CALLE 33", "CALLE 40", "EL VALLE", "CALLE 44", "DIAGONAL", "CALLE 51", "CALLE 77", "CALLE 78",
        "CALLE 85", "CHARLONE", "CHARRUAS", "CHINGOLO", "CALLE 13", "CALLE 48", "CALLE 50", "CALLE 66",
        "CALLE 68", "EL ZAINO", "HERRERIA", "MALVINAS", "MANSILLA", "LA BRAVA", "PEUMAYEN", "PORTUGAL",
        "PRAXEDES", "RIO MAYO", "PATRICIA", "SANTA FE", "SAN LUIS", "ARENALES", "ASTURIAS", "LIBERTAD",
        "VICTORIA", "AYACUCHO", "BALCARCE", "BAUTISTA", "VIRGINIA", "BELGRANO", "BELL MAR", "B/P FOCA",
        "BRANDSEN", "CALLE 10", "CALABRIA", "CALLE 11", "CALLE 12", "CALLE 15", "CALLE 16", "CALLE 17",
        "CALLE 18", "CALLE 19", "CALLE 20", "CALLE 23", "CALLE 24", "CALLE 25", "CALLE 26", "CALLE 27",
        "CALLE 31", "CALLE 32", "CALLE 34", "CALLE 35", "CALLE 36", "CALLE 37", "CALLE 38", "CALLE 39",
        "39 BIS B", "CALLE 41", "CALLE 42", "CALLE 43", "CALLE 45", "CALLE 46", "CALLE 47", "CALLE 49",
        "CALLE 67", "CALLE 52", "CALLE 53", "CALLE 54", "CALLE 55", "CALLE 56", "CALLE 57", "CALLE 58",
        "CALLE 59", "CALLE 79", "CALLE 69", "CALLE 60", "CALLE 61", "CALLE 62", "CALLE 63", "CALLE 64",
        "CALLE 65", "CALLE 70", "CALLE 71", "CALLE 72", "CALLE 73", "CALLE 74", "CALLE 75", "CALLE 76",
        "CALLE 81", "CALLE 82", "CALLE 83", "CALLE 80", "CALLE 87", "CALLE 89", "EL CERRO", "EL CHAJA",
        "EL MATEO", "EL MIXTO", "EL MONTE", "EL RODEO", "EL SULKY", "EL TORDO", "ESC. SUR", "CIPRESES",
        "EVARISTO", "FAUSTINO", "GRACIELA", "GREGORIO", "GUERNICA", "JOSEFINA", "LA POSTA", "LAMADRID",
        "LA PAMPA", "LA RIOJA", "LITUANIA", "LOS TALA", "LABARDEN", "MENENDEZ", "MERCEDES", "MISIONES",
        "MOCOBIES", "MONSALVO", "LA LAURA", "LA LEGUA", "NECOCHEA", "NOGUEIRA", "NORBERTO", "PARAGUAY",
        "PRINGLES", "PUCO YAN", "PUELCHES", "SAN JUAN", "RUMEN CO", "VALENCIA", "VERONICA", "VIAMONTE",
        "173 BIS", "175 BIS", "177 BIS", "179 BIS", "183 BIS", "211 BIS", "270 BIS", "272 BIS",
        "433 BIS", "ACACIAS", "ADRIANA", "CALLE 9", "CAROYAS", "CASEROS", "CECILIA", "CERRITO",
        "CALLE 2", "248 BIS", "CORDOBA", "DANIELA", "709 BIS", "CALLE 6", "CALLE 8", "DOMINGO",
        "DOROTEA", "DORREGO", "ECUADOR", "CLAUDIA", "HUARPES", "IGNACIO", "711 BIS", "LA TABA",
        "EUGENIA", "LUCANIA", "LUCIANO", "697 BIS", "HILARIO", "MANGORE", "PIERINA", "PILAGAS",
        "PIÑACAL", "POLONIA", "POSADAS", "PASTEUR", "RICARDO", "RODOLFO", "RONDEAU", "TOSCANA",
        "TUCUMAN", "URUGUAY", "USHUAIA", "ARMANDO", "ARMENIA", "705 BIS", "PAMPERO", "PIONERO",
        "CALLE 1", "VIEYTES", "181 BIS", "BEATRIZ", "BELGICA", "201 BIS", "203 BIS", "209 BIS",
        "BERMEJO", "BOLIVAR", "BOLIVIA", "BRAULIO", "BRIGIDA", "CABILDO", "CALLE 0", "ALELIES",
        "771 BIS", "CALLE14", "CALLE 4", "CALLE 3", "431 BIS", "427 BIS", "429 BIS", "CALLE 5",
        "507 BIS", "513 BIS", "687 BIS", "CALLE 7", "719 BIS", "791 BIS", "793 BIS", "801 BIS",
        "819 BIS", "823 BIS", "EL CANO", "EL LAZO", "EL TERO", "ENRIQUE", "CHOCORI", "EVELINA",
        "FALUCHO", "FORMOSA", "FRANCIA", "GABRIEL", "GALICIA", "GUAYANA", "ISIDORO", "CENTRAL",
        "JACINTO", "JOAQUIN", "LAPRIDA", "LEANDRO", "LEGH II", "LETICIA", "LILIANA", "LINIERS",
        "LOBERIA", "HERMIDA", "MARCELA", "MARIANA", "MARIANO", "LAFQUEN", "PEHUAJO", "MATILDE",
        "MELINAO", "MENDOZA", "TINGUES", "LA LOMA", "NAPOLES", "NARCISO", "NATALIA", "NEUQUEN",
        "OLLEROS", "OSVALDO", "PASCUAL", "SICILIA", "ROBERTO", "ROTONDA", "YOLANDA", "12 BIS",
        "13 BIS", "ALICIA", "ANALIA", "ANGELA", "CANADA", "CANNES", "CARLOS", "CATANI",
        "CEDROS", "DAMIAN", "DANIEL", "DERQUI", "67 BIS", "CAMILO", "TERESA", "HAYDIN",
        "HECTOR", "HUILEN", "ESTELA", "HIGINO", "JUNCAL", "JULIAN", "MARCOS", "PINCEN",
        "SILVIA", "RAWSON", "ARAGON", "AROMOS", "ARTURO", "11 BIS", "MARLIN", "VERTIZ",
        "VICTOR", "AYELEP", "VIEDMA", "AYOLAS", "ALTAIR", "FOCA B", "BRASIL", "69 BIS",
        "TANDIL", "10 BIS", "ADOLFO", "ALSINA", "ALVARO", "14 BIS", "VULCAN", "27 BIS",
        "WALTER", "22 BIS", "28 BIS", "30 BIS", "32 BIS", "34 BIS", "36 BIS", "39 BIS",
        "33 BIS", "40 BIS", "41 BIS", "45 BIS", "48 BIS", "63 BIS", "65 BIS", "86 BIS",
        "89 BIS", "EGIDIO", "EMILIO", "CHUBUT", "ESPAÑA", "FABIAN", "FELIPE", "FRANCA",
        "FRIULI", "GABOTO", "GENARO", "GENOVA", "GRECIA", "ISABEL", "ITALIA", "ESQUEL",
        "LARREA", "LLIFEN", "MARTIN", "MEJICO", "MIGUEL", "PELAYO", "PERDIZ", "MORENO",
        "NESTOR", "OFELIA", "OVIDIO", "PARANA", "RAQUEL", "SUSANA", "ROSANA", "YAPEYU",
        "ZURITA", "ANGEL", "DARDO", "NORTE", "DIEGO", "695 B", "HUDER", "JUANA",
        "LUCIO", "LUISA", "HILDA", "JUSTO", "PIGUE", "SIOUX", "SOFIA", "PAULA",
        "TULIO", "TUPAC", "UDINE", "COLON", "BASSI", "BRUNO", "0 BIS", "2 BIS",
        "4 BIS", "6 BIS", "8 BIS", "ELENA", "CHACO", "ELINA", "ELISA", "CHILE",
        "FARRO", "FELIX", "IRALA", "IRENE", "JORGE", "JUJUY", "JULIA", "LAURA",
        "LIDIA", "ESTER", "LULES", "MABEL", "MAIPU", "MARIA", "MARIO", "MARTA",
        "MAURO", "MIRTA", "NOEMI", "TOBAS", "OSCAR", "PABLO", "PEDRO", "SALTA",
        "SOLIS", "TAGLE", "14 B", "SARA", "13 B", "20 B", "OMBU", "INES",
        "JUAN", "LUIS", "PERU", "ROSA", "ABEL", "FOCA", "10 B", "11 B",
        "ACHA", "ALDO", "12 B", "15 B", "16 B", "17 B", "18 B", "19 B",
        "22 B", "23 B", "24 B", "25 B", "27 B", "30 B", "31 B", "53 B",
        "55 B", "56 B", "ELSA", "JOSE", "NN A", "NN B", "NORA", "OLGA",
        "PUAN", "RITA", "RUIZ", "128", "9 B", "9 C", "455", "497",
        "4 B", "707", "709", "711", "SUR", "509", "719", "693",
        "6 B", "697", "236", "S/N", "136", "LIA", "238", "699",
        "232", "234", "250", "843", "204", "206", "101", "103",
        "105", "107", "208", "142", "159", "160", "194", "196",
        "198", "1 B", "1 C", "200", "202", "228", "2 B", "2 C",
        "3 B", "3 C", "429", "445", "447", "449", "451", "453",
        "457", "459", "461", "463", "465", "467", "471", "473",
        "475", "477", "479", "481", "483", "485", "487", "489",
        "491", "493", "495", "499", "4 C", "501", "503", "505",
        "507", "511", "513", "5 B", "5 C", "797", "6 C", "701",
        "703", "705", "713", "715", "717", "7 B", "721", "723",
        "725", "727", "729", "731", "733", "735", "737", "739",
        "741", "743", "745", "747", "749", "751", "753", "755",
        "757", "759", "761", "763", "765", "767", "769", "771",
        "773", "775", "777", "779", "781", "783", "785", "787",
        "789", "791", "793", "795", "799", "801", "803", "805",
        "807", "809", "811", "813", "815", "817", "819", "821",
        "823", "825", "827", "829", "831", "833", "835", "837",
        "839", "841", "845", "847", "849", "851", "853", "8 B",
        "EMA", "EVA"
    ];

    let filtros = {
        rojo: ["marzo", "diciembre", "estudiantes", "estudiante", "estudiantil", "temporal", "9 meses", "12 meses", "sin gas", "reservado", "temporada", "ICL"],
        verde: ["24 meses", "lavadero", "garantia propietaria"],
        amarillo: ["recibo de sueldo", "demostracion de ingresos", "USD"]
    };

    const LIMITE = 780000;
    const regexMontos = /(?:(?:U\$S|\$)\s?)?(?:\d{1,3}(?:[.,]\d{3})+|\d{6,})(?!\d)/gi;

    // Improved Regex to handle "al", commas, and spaces
    const regexDireccion = new RegExp(`\\b(${STREETS.join("|")})\\s*(?:,\\s*|al\\s+|al\\s*,\\s*)*(\\d+)\\b`, "gi");

    // Persistence for 'seen' apartments
    let seenApartments = GM_getValue('seen_apartments', []);

    GM_addStyle(`
        .visto-btn { margin-left: 5px; padding: 2px 5px; font-size: 10px; cursor: pointer; background: #666; color: white; border: 1px solid #999; border-radius: 3px; }
        .visto-btn:hover { background: #444; }
        .visto-btn.active { background: #28a745; border-color: #1e7e34; }
        .address-seen { text-decoration: line-through; opacity: 0.6; }
    `);

    function normalizarMonto(str) {
        return parseInt(str.replace(/U\$S|\$/gi, "").replace(/[.,\s]/g, ""), 10);
    }

    function toggleVisto ✓(id, btn, span) {
        if (seenApartments.includes(id)) {
            seenApartments = seenApartments.filter(a => a !== id);
            btn.classList.remove('active');
            span.classList.remove('address-seen');
            btn.textContent = "visto";
        } else {
            seenApartments.push(id);
            btn.classList.add('active');
            span.classList.add('address-seen');
            btn.textContent = "âœ“";
        }
        GM_setValue('seen_apartments', seenApartments);
    }

    function marcar(node) {
        if (node.nodeType === 1 && ["SCRIPT", "STYLE", "TEXTAREA", "INPUT", "NOSCRIPT"].includes(node.tagName)) return;

        if (node.nodeType === 3) {
            let text = node.nodeValue;
            if (!text || text.trim().length === 0) return;
            if (node.parentNode && node.parentNode.hasAttribute && node.parentNode.hasAttribute('data-filtro')) return;

            let hasMatches = false;
            let parts = [{ type: 'text', value: text }];

            const applyFilter = (regex, type, style, isAddress = false) => {
                let newParts = [];
                parts.forEach(part => {
                    if (part.type !== 'text') {
                        newParts.push(part);
                        return;
                    }
                    let lastIndex = 0;
                    let match;
                    regex.lastIndex = 0;
                    while ((match = regex.exec(part.value)) !== null) {
                        if (match.index > lastIndex) {
                            newParts.push({ type: 'text', value: part.value.substring(lastIndex, match.index) });
                        }

                        let shouldHighlight = true;
                        if (type === 'precio') {
                            const v = normalizarMonto(match[0]);
                            if (isNaN(v) || v < LIMITE) shouldHighlight = false;
                        }

                        if (shouldHighlight) {
                            newParts.push({ type: 'span', value: match[0], marker: type, style: style, isAddress: isAddress });
                            hasMatches = true;
                        } else {
                            newParts.push({ type: 'text', value: match[0] });
                        }
                        lastIndex = regex.lastIndex;
                    }
                    if (lastIndex < part.value.length) {
                        newParts.push({ type: 'text', value: part.value.substring(lastIndex) });
                    }
                });
                parts = newParts;
            };

            // Apply Filters
            Object.keys(filtros).forEach(color => {
                let style = color === "rojo" ? "background:red;color:white;font-weight:bold;" :
                    color === "verde" ? "background:limegreen;color:black;font-weight:bold;" :
                        "background:gold;color:black;font-weight:bold;";
                filtros[color].forEach(word => applyFilter(new RegExp(`(${word})`, "gi"), color, style));
            });
            applyFilter(regexMontos, 'precio', "background:red;color:white;font-weight:bold;");
            applyFilter(regexDireccion, 'direccion', "background:cyan;color:black;", true);

            if (hasMatches) {
                const fragment = document.createDocumentFragment();
                parts.forEach(part => {
                    if (part.type === 'text') {
                        fragment.appendChild(document.createTextNode(part.value));
                    } else {
                        const span = document.createElement('span');
                        span.setAttribute('data-filtro', part.marker);
                        span.style.cssText = part.style;
                        span.textContent = part.value;

                        if (part.isAddress) {
                            // Normalize ID for seenApartments: remove "al", commas, multiple spaces
                            const addrId = part.value.toUpperCase().replace(/[^A-Z0-9]/g, ' ').replace(/\s+/g, ' ').trim();
                            const btn = document.createElement('button');
                            btn.className = 'visto-btn';
                            btn.textContent = seenApartments.includes(addrId) ? "Visto ✓✓" : "visto";
                            if (seenApartments.includes(addrId)) {
                                btn.classList.add('active');
                                span.classList.add('address-seen');
                            }
                            btn.onclick = (e) => {
                                e.preventDefault();
                                e.stopPropagation();
                                toggleVisto ✓(addrId, btn, span);
                            };
                            fragment.appendChild(span);
                            fragment.appendChild(btn);
                        } else {
                            fragment.appendChild(span);
                        }
                    }
                });
                try {
                    if (node.parentNode) node.parentNode.replaceChild(fragment, node);
                } catch (e) {
                    console.warn("[Rent Filter] Failed to replace node:", e);
                }
            }
        } else {
            Array.from(node.childNodes).forEach(marcar);
        }
    }

    /* ===== OBSERVER ===== */
    let observer;
    function startObserving() {
        if (observer) observer.disconnect();
        observer = new MutationObserver((mutations) => {
            mutations.forEach((mutation) => {
                mutation.addedNodes.forEach((node) => marcar(node));
            });
        });
        observer.observe(document.body, { childList: true, subtree: true });
    }

    function aplicarTodo() {
        marcar(document.body);
        startObserving();
    }

    /* ===== UI ELEMENTS ===== */
    function setupUI() {
        const btn = document.createElement("button");
        btn.textContent = "âš™";
        btn.id = "rf-settings-btn";
        btn.style.cssText = "position:fixed; bottom:10px; right:10px; z-index:999999; padding:8px; border-radius:8px; cursor:pointer; background:#222; color:#fff; border:1px solid #555;";
        document.body.appendChild(btn);

        const updateBtn = document.createElement("button");
        updateBtn.textContent = "ðŸ”„";
        updateBtn.style.cssText = "position:fixed; bottom:55px; right:10px; z-index:999999; padding:8px; border-radius:50%; cursor:pointer; background:black; color:white; border:1px solid white; font-size:14px;";
        updateBtn.onclick = () => window.open("https://raw.githubusercontent.com/Wapply/word-filter/main/rent-filter.user.js", "_blank");
        document.body.appendChild(updateBtn);

        const panel = document.createElement("div");
        panel.id = "rf-panel";
        panel.style.cssText = "position:fixed; bottom:100px; right:10px; background:#111; color:#fff; padding:10px; border-radius:10px; font-size:12px; display:none; z-index:999999; max-width:260px; border: 1px solid #444;";

        function renderPanel() {
            panel.innerHTML = "";
            Object.keys(filtros).forEach(color => {
                const titulo = document.createElement("b");
                titulo.textContent = color.toUpperCase();
                panel.appendChild(titulo);
                panel.appendChild(document.createElement("br"));
                filtros[color].forEach((f, i) => {
                    const row = document.createElement("div");
                    row.style.margin = "2px 0";
                    row.innerHTML = `<span style="display:inline-block; width:180px; overflow:hidden; text-overflow:ellipsis; white-space:nowrap;">${f}</span>
                                     <button style="background:red; color:white; border:none; border-radius:3px; cursor:pointer;" data-c="${color}" data-i="${i}">âœ–</button>`;
                    panel.appendChild(row);
                });
                const input = document.createElement("input");
                input.placeholder = "Agregar...";
                input.style.cssText = "width:100%; margin-top:4px; background:#fff; color:#000; border-radius:4px; padding:3px;";
                input.onkeydown = e => {
                    if (e.key === "Enter" && input.value.trim()) {
                        filtros[color].push(input.value.trim());
                        input.value = "";
                        renderPanel(); aplicarTodo();
                    }
                };
                panel.appendChild(input);
                panel.appendChild(document.createElement("br"));
            });
            panel.querySelectorAll("button[data-c]").forEach(b => {
                b.onclick = () => {
                    filtros[b.dataset.c].splice(b.dataset.i, 1);
                    renderPanel(); aplicarTodo();
                };
            });
        }
        btn.onclick = () => {
            panel.style.display = panel.style.display === "none" ? "block" : "none";
            renderPanel();
        };
        document.body.appendChild(panel);
    }

    if (document.readyState === "complete" || document.readyState === "interactive") {
        setupUI(); aplicarTodo();
    } else {
        window.addEventListener("DOMContentLoaded", () => { setupUI(); aplicarTodo(); });
    }
})();



